// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloPlan = "galloPlans"

// GalloPlan 用户套餐
type GalloPlan struct {
	ID                          int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                                 // ID
	IsOn                        bool    `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                                               // 是否启用
	Name                        string  `gorm:"column:name;comment:套餐名" json:"name"`                                                          // 套餐名
	Description                 string  `gorm:"column:description;comment:套餐简介" json:"description"`                                           // 套餐简介
	ClusterID                   int32   `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`                                               // 集群ID
	TrafficLimit                string  `gorm:"column:trafficLimit;comment:流量限制" json:"trafficLimit"`                                         // 流量限制
	BandwidthLimitPerNode       string  `gorm:"column:bandwidthLimitPerNode;comment:单节点带宽限制" json:"bandwidthLimitPerNode"`                    // 单节点带宽限制
	Features                    string  `gorm:"column:features;comment:允许的功能" json:"features"`                                                // 允许的功能
	HasFullFeatures             bool    `gorm:"column:hasFullFeatures;default:1;comment:是否有完整的功能" json:"hasFullFeatures"`                     // 是否有完整的功能
	TrafficPrice                string  `gorm:"column:trafficPrice;comment:流量价格设定" json:"trafficPrice"`                                       // 流量价格设定
	BandwidthPrice              string  `gorm:"column:bandwidthPrice;comment:带宽价格" json:"bandwidthPrice"`                                     // 带宽价格
	MonthlyPrice                float64 `gorm:"column:monthlyPrice;default:0.00;comment:月付" json:"monthlyPrice"`                              // 月付
	SeasonallyPrice             float64 `gorm:"column:seasonallyPrice;default:0.00;comment:季付" json:"seasonallyPrice"`                        // 季付
	YearlyPrice                 float64 `gorm:"column:yearlyPrice;default:0.00;comment:年付" json:"yearlyPrice"`                                // 年付
	PriceType                   string  `gorm:"column:priceType;comment:价格类型" json:"priceType"`                                               // 价格类型
	Order                       int32   `gorm:"column:order;comment:排序" json:"order"`                                                         // 排序
	State                       bool    `gorm:"column:state;default:1;comment:状态" json:"state"`                                               // 状态
	TotalServers                int32   `gorm:"column:totalServers;default:1;comment:可以绑定的网站数量" json:"totalServers"`                          // 可以绑定的网站数量
	TotalServerNamesPerServer   int32   `gorm:"column:totalServerNamesPerServer;comment:每个网站可以绑定的域名数量" json:"totalServerNamesPerServer"`      // 每个网站可以绑定的域名数量
	TotalServerNames            int32   `gorm:"column:totalServerNames;comment:总域名数量" json:"totalServerNames"`                                // 总域名数量
	MonthlyRequests             int64   `gorm:"column:monthlyRequests;comment:每月访问量额度" json:"monthlyRequests"`                                // 每月访问量额度
	DailyRequests               int64   `gorm:"column:dailyRequests;comment:每日访问量额度" json:"dailyRequests"`                                    // 每日访问量额度
	DailyWebsocketConnections   int64   `gorm:"column:dailyWebsocketConnections;comment:每日Websocket连接数" json:"dailyWebsocketConnections"`     // 每日Websocket连接数
	MonthlyWebsocketConnections int64   `gorm:"column:monthlyWebsocketConnections;comment:每月Websocket连接数" json:"monthlyWebsocketConnections"` // 每月Websocket连接数
	MaxUploadSize               string  `gorm:"column:maxUploadSize;comment:最大上传" json:"maxUploadSize"`                                       // 最大上传
}

// TableName GalloPlan's table name
func (*GalloPlan) TableName() string {
	return TableNameGalloPlan
}
