// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloSysSetting = "galloSysSettings"

// GalloSysSetting 系统配置
type GalloSysSetting struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Code   string `gorm:"column:code;comment:代号" json:"code"`                           // 代号
	Value  string `gorm:"column:value;comment:配置值" json:"value"`                        // 配置值
}

// TableName GalloSysSetting's table name
func (*GalloSysSetting) TableName() string {
	return TableNameGalloSysSetting
}
