// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerBill = "galloServerBills"

// GalloServerBill 服务账单
type GalloServerBill struct {
	ID                       int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                    // ID
	UserID                   int32   `gorm:"column:userId;comment:用户ID" json:"userId"`                                        // 用户ID
	ServerID                 int32   `gorm:"column:serverId;comment:服务ID" json:"serverId"`                                    // 服务ID
	Amount                   float64 `gorm:"column:amount;default:0.00;comment:金额" json:"amount"`                             // 金额
	Month                    string  `gorm:"column:month;comment:月份" json:"month"`                                            // 月份
	CreatedAt                int64   `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                                  // 创建时间
	UserPlanID               int32   `gorm:"column:userPlanId;comment:用户套餐ID" json:"userPlanId"`                              // 用户套餐ID
	PlanID                   int32   `gorm:"column:planId;comment:套餐ID" json:"planId"`                                        // 套餐ID
	TotalTrafficBytes        int64   `gorm:"column:totalTrafficBytes;comment:总流量" json:"totalTrafficBytes"`                   // 总流量
	BandwidthPercentileBytes int64   `gorm:"column:bandwidthPercentileBytes;comment:带宽百分位字节" json:"bandwidthPercentileBytes"` // 带宽百分位字节
	BandwidthPercentile      int32   `gorm:"column:bandwidthPercentile;comment:带宽百分位" json:"bandwidthPercentile"`             // 带宽百分位
	PriceType                string  `gorm:"column:priceType;comment:计费类型" json:"priceType"`                                  // 计费类型
}

// TableName GalloServerBill's table name
func (*GalloServerBill) TableName() string {
	return TableNameGalloServerBill
}
