// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloMessage = "galloMessages"

// GalloMessage 消息通知
type GalloMessage struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID   int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID    int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Role      string `gorm:"column:role;default:node;comment:角色" json:"role"`              // 角色
	ClusterID int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	NodeID    int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                     // 节点ID
	Level     string `gorm:"column:level;comment:级别" json:"level"`                         // 级别
	Subject   string `gorm:"column:subject;comment:标题" json:"subject"`                     // 标题
	Body      string `gorm:"column:body" json:"body"`
	Type      string `gorm:"column:type;comment:消息类型" json:"type"`           // 消息类型
	Params    string `gorm:"column:params;comment:额外的参数" json:"params"`      // 额外的参数
	IsRead    bool   `gorm:"column:isRead;comment:是否已读" json:"isRead"`       // 是否已读
	State     bool   `gorm:"column:state;default:1;comment:状态" json:"state"` // 状态
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"` // 创建时间
	Day       string `gorm:"column:day;comment:日期YYYYMMDD" json:"day"`       // 日期YYYYMMDD
	Hash      string `gorm:"column:hash;comment:消息内容的Hash" json:"hash"`      // 消息内容的Hash
}

// TableName GalloMessage's table name
func (*GalloMessage) TableName() string {
	return TableNameGalloMessage
}
