// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserAccessKey = "galloUserAccessKeys"

// GalloUserAccessKey AccessKey
type GalloUserAccessKey struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID     int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID      int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	SubUserID   int32  `gorm:"column:subUserId;comment:子用户ID" json:"subUserId"`              // 子用户ID
	IsOn        bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	UniqueID    string `gorm:"column:uniqueId;comment:唯一的Key" json:"uniqueId"`               // 唯一的Key
	Secret      string `gorm:"column:secret;comment:密钥" json:"secret"`                       // 密钥
	Description string `gorm:"column:description;comment:备注" json:"description"`             // 备注
	AccessedAt  int64  `gorm:"column:accessedAt;comment:最近一次访问时间" json:"accessedAt"`         // 最近一次访问时间
	State       bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloUserAccessKey's table name
func (*GalloUserAccessKey) TableName() string {
	return TableNameGalloUserAccessKey
}
