// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodePriceItem = "galloNodePriceItems"

// GalloNodePriceItem 区域计费设置
type GalloNodePriceItem struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	IsOn      bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Type      string `gorm:"column:type;comment:类型：峰值|流量" json:"type"`                     // 类型：峰值|流量
	Name      string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	BitsFrom  int64  `gorm:"column:bitsFrom;comment:起始值" json:"bitsFrom"`                  // 起始值
	BitsTo    int64  `gorm:"column:bitsTo;comment:结束值" json:"bitsTo"`                      // 结束值
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	State     bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNodePriceItem's table name
func (*GalloNodePriceItem) TableName() string {
	return TableNameGalloNodePriceItem
}
