// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloClientSystem = "galloClientSystems"

// GalloClientSystem 终端操作系统信息
type GalloClientSystem struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`              // ID
	Name       string `gorm:"column:name;comment:系统名称" json:"name"`                                      // 系统名称
	Codes      string `gorm:"column:codes;comment:代号" json:"codes"`                                      // 代号
	CreatedDay string `gorm:"column:createdDay;default:00000000;comment:创建日期YYYYMMDD" json:"createdDay"` // 创建日期YYYYMMDD
	State      bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                            // 状态
}

// TableName GalloClientSystem's table name
func (*GalloClientSystem) TableName() string {
	return TableNameGalloClientSystem
}
