// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloClientAgentIP = "galloClientAgentIPs"

// GalloClientAgentIP Agent IP
type GalloClientAgentIP struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AgentID int32  `gorm:"column:agentId;comment:Agent ID" json:"agentId"`               // Agent ID
	IP      string `gorm:"column:ip;comment:IP地址" json:"ip"`                             // IP地址
	Ptr     string `gorm:"column:ptr;comment:PTR值" json:"ptr"`                           // PTR值
}

// TableName GalloClientAgentIP's table name
func (*GalloClientAgentIP) TableName() string {
	return TableNameGalloClientAgentIP
}
