// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloDNSDomain = "galloDNSDomains"

// GalloDNSDomain 管理的域名
type GalloDNSDomain struct {
	ID            int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID       int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID        int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	ProviderID    int32  `gorm:"column:providerId;comment:服务商ID" json:"providerId"`            // 服务商ID
	IsOn          bool   `gorm:"column:isOn;default:1;comment:是否可用" json:"isOn"`               // 是否可用
	Name          string `gorm:"column:name;comment:域名" json:"name"`                           // 域名
	CreatedAt     int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	DataUpdatedAt int64  `gorm:"column:dataUpdatedAt;comment:数据更新时间" json:"dataUpdatedAt"`     // 数据更新时间
	DataError     string `gorm:"column:dataError;comment:数据更新错误" json:"dataError"`             // 数据更新错误
	Data          string `gorm:"column:data;comment:原始数据信息" json:"data"`                       // 原始数据信息
	Records       string `gorm:"column:records;comment:所有解析记录" json:"records"`                 // 所有解析记录
	Routes        string `gorm:"column:routes;comment:线路数据" json:"routes"`                     // 线路数据
	IsUp          bool   `gorm:"column:isUp;default:1;comment:是否在线" json:"isUp"`               // 是否在线
	State         bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	IsDeleted     bool   `gorm:"column:isDeleted;comment:是否已删除" json:"isDeleted"`              // 是否已删除
}

// TableName GalloDNSDomain's table name
func (*GalloDNSDomain) TableName() string {
	return TableNameGalloDNSDomain
}
