// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloMessageMedia = "galloMessageMedias"

// GalloMessageMedia 消息媒介
type GalloMessageMedia struct {
	ID              int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name            string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	Type            string `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	Description     string `gorm:"column:description;comment:描述" json:"description"`             // 描述
	UserDescription string `gorm:"column:userDescription;comment:用户描述" json:"userDescription"`   // 用户描述
	IsOn            bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Order           int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	State           bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloMessageMedia's table name
func (*GalloMessageMedia) TableName() string {
	return TableNameGalloMessageMedia
}
