// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloACMEUser = "galloACMEUsers"

// GalloACMEUser ACME用户
type GalloACMEUser struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`              // ID
	AdminID      int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                               // 管理员ID
	UserID       int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                                  // 用户ID
	PrivateKey   string `gorm:"column:privateKey;comment:私钥" json:"privateKey"`                            // 私钥
	Email        string `gorm:"column:email;comment:E-mail" json:"email"`                                  // E-mail
	CreatedAt    int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                            // 创建时间
	State        bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                            // 状态
	Description  string `gorm:"column:description;comment:备注介绍" json:"description"`                        // 备注介绍
	Registration string `gorm:"column:registration;comment:注册信息" json:"registration"`                      // 注册信息
	ProviderCode string `gorm:"column:providerCode;default:letsencrypt;comment:服务商代号" json:"providerCode"` // 服务商代号
	AccountID    int64  `gorm:"column:accountId;comment:提供商ID" json:"accountId"`                           // 提供商ID
}

// TableName GalloACMEUser's table name
func (*GalloACMEUser) TableName() string {
	return TableNameGalloACMEUser
}
