// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSZone = "galloNSZones"

// GalloNSZone 域名子域
type GalloNSZone struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	DomainID int64  `gorm:"column:domainId;comment:域名ID" json:"domainId"`                 // 域名ID
	IsOn     bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Order    int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	Version  int64  `gorm:"column:version;comment:版本" json:"version"`                     // 版本
	Tsig     string `gorm:"column:tsig;comment:TSIG配置" json:"tsig"`                       // TSIG配置
	State    bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNSZone's table name
func (*GalloNSZone) TableName() string {
	return TableNameGalloNSZone
}
