// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloIPLibraryFile = "galloIPLibraryFiles"

// GalloIPLibraryFile IP库上传的文件
type GalloIPLibraryFile struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`  // ID
	Name            string `gorm:"column:name;comment:IP库名称" json:"name"`                         // IP库名称
	FileID          int64  `gorm:"column:fileId;comment:原始文件ID" json:"fileId"`                    // 原始文件ID
	Template        string `gorm:"column:template;comment:模板" json:"template"`                    // 模板
	EmptyValues     string `gorm:"column:emptyValues;comment:空值列表" json:"emptyValues"`            // 空值列表
	GeneratedFileID int64  `gorm:"column:generatedFileId;comment:生成的文件ID" json:"generatedFileId"` // 生成的文件ID
	GeneratedAt     int64  `gorm:"column:generatedAt;comment:生成时间" json:"generatedAt"`            // 生成时间
	IsFinished      bool   `gorm:"column:isFinished;comment:是否已经完成" json:"isFinished"`            // 是否已经完成
	Countries       string `gorm:"column:countries;comment:国家/地区" json:"countries"`               // 国家/地区
	Provinces       string `gorm:"column:provinces;comment:省份" json:"provinces"`                  // 省份
	Cities          string `gorm:"column:cities;comment:城市" json:"cities"`                        // 城市
	Towns           string `gorm:"column:towns;comment:区县" json:"towns"`                          // 区县
	Providers       string `gorm:"column:providers;comment:ISP服务商" json:"providers"`              // ISP服务商
	Code            string `gorm:"column:code;comment:文件代号" json:"code"`                          // 文件代号
	Password        string `gorm:"column:password;comment:密码" json:"password"`                    // 密码
	CreatedAt       int64  `gorm:"column:createdAt;comment:上传时间" json:"createdAt"`                // 上传时间
	State           bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                // 状态
}

// TableName GalloIPLibraryFile's table name
func (*GalloIPLibraryFile) TableName() string {
	return TableNameGalloIPLibraryFile
}
