// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

import (
	"time"
)

const TableNameGalloMessageRecipient = "galloMessageRecipients"

// GalloMessageRecipient 消息媒介接收人
type GalloMessageRecipient struct {
	ID          int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID     int32     `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	IsOn        bool      `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	InstanceID  int32     `gorm:"column:instanceId;comment:实例ID" json:"instanceId"`             // 实例ID
	User        string    `gorm:"column:user;comment:接收人信息" json:"user"`                        // 接收人信息
	GroupIds    string    `gorm:"column:groupIds;comment:分组ID" json:"groupIds"`                 // 分组ID
	State       bool      `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	TimeFrom    time.Time `gorm:"column:timeFrom;comment:开始时间" json:"timeFrom"`                 // 开始时间
	TimeTo      time.Time `gorm:"column:timeTo;comment:结束时间" json:"timeTo"`                     // 结束时间
	Description string    `gorm:"column:description;comment:备注" json:"description"`             // 备注
}

// TableName GalloMessageRecipient's table name
func (*GalloMessageRecipient) TableName() string {
	return TableNameGalloMessageRecipient
}
