// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserEmailNotification = "galloUserEmailNotifications"

// GalloUserEmailNotification 邮件通知队列
type GalloUserEmailNotification struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Email     string `gorm:"column:email;comment:邮箱地址" json:"email"`                       // 邮箱地址
	Subject   string `gorm:"column:subject;comment:标题" json:"subject"`                     // 标题
	Body      string `gorm:"column:body;comment:内容" json:"body"`                           // 内容
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	Day       string `gorm:"column:day;comment:YYYYMMDD" json:"day"`                       // YYYYMMDD
}

// TableName GalloUserEmailNotification's table name
func (*GalloUserEmailNotification) TableName() string {
	return TableNameGalloUserEmailNotification
}
