// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerStatBoardChart = "galloServerStatBoardCharts"

// GalloServerStatBoardChart 服务看板中的图表
type GalloServerStatBoardChart struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	BoardID int64  `gorm:"column:boardId;comment:看板ID" json:"boardId"`                   // 看板ID
	Code    string `gorm:"column:code;comment:内置图表代码" json:"code"`                       // 内置图表代码
	ItemID  int32  `gorm:"column:itemId;comment:指标ID" json:"itemId"`                     // 指标ID
	ChartID int32  `gorm:"column:chartId;comment:图表ID" json:"chartId"`                   // 图表ID
	Order   int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	State   bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloServerStatBoardChart's table name
func (*GalloServerStatBoardChart) TableName() string {
	return TableNameGalloServerStatBoardChart
}
