// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloMetricStat = "galloMetricStats"

// GalloMetricStat 指标统计数据
type GalloMetricStat struct {
	ID         int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Hash       string  `gorm:"column:hash;comment:Hash值" json:"hash"`                        // Hash值
	ClusterID  int32   `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	NodeID     int32   `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                     // 节点ID
	ServerID   int32   `gorm:"column:serverId;comment:服务ID" json:"serverId"`                 // 服务ID
	ItemID     int64   `gorm:"column:itemId;comment:指标" json:"itemId"`                       // 指标
	Keys       string  `gorm:"column:keys;comment:键值" json:"keys"`                           // 键值
	Value      float64 `gorm:"column:value;default:0.00;comment:数值" json:"value"`            // 数值
	Time       string  `gorm:"column:time;comment:分钟值YYYYMMDDHHII" json:"time"`              // 分钟值YYYYMMDDHHII
	Version    int32   `gorm:"column:version;comment:版本号" json:"version"`                    // 版本号
	CreatedDay string  `gorm:"column:createdDay;comment:YYYYMMDD" json:"createdDay"`         // YYYYMMDD
}

// TableName GalloMetricStat's table name
func (*GalloMetricStat) TableName() string {
	return TableNameGalloMetricStat
}
