// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserTicketLog = "galloUserTicketLogs"

// GalloUserTicketLog 工单日志
type GalloUserTicketLog struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID    int64  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID     int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	TicketID   int64  `gorm:"column:ticketId;comment:工单ID" json:"ticketId"`                 // 工单ID
	Status     string `gorm:"column:status;comment:状态" json:"status"`                       // 状态
	Comment    string `gorm:"column:comment;comment:回复内容" json:"comment"`                   // 回复内容
	CreatedAt  int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	IsReadonly bool   `gorm:"column:isReadonly;comment:是否为只读" json:"isReadonly"`            // 是否为只读
	State      bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloUserTicketLog's table name
func (*GalloUserTicketLog) TableName() string {
	return TableNameGalloUserTicketLog
}
