// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerRegionProvinceMonthlyStat = "galloServerRegionProvinceMonthlyStats"

// GalloServerRegionProvinceMonthlyStat 服务用户省份分布统计（按天）
type GalloServerRegionProvinceMonthlyStat struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ServerID   int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                 // 服务ID
	ProvinceID int32  `gorm:"column:provinceId;comment:省份ID" json:"provinceId"`             // 省份ID
	Month      string `gorm:"column:month;comment:月份YYYYMM" json:"month"`                   // 月份YYYYMM
	Count      int64  `gorm:"column:count;comment:数量" json:"count"`                         // 数量
}

// TableName GalloServerRegionProvinceMonthlyStat's table name
func (*GalloServerRegionProvinceMonthlyStat) TableName() string {
	return TableNameGalloServerRegionProvinceMonthlyStat
}
