// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPDeflatePolicy = "galloHTTPDeflatePolicies"

// GalloHTTPDeflatePolicy Gzip配置
type GalloHTTPDeflatePolicy struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID   int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID    int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	IsOn      bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Level     int32  `gorm:"column:level;comment:压缩级别" json:"level"`                       // 压缩级别
	MinLength string `gorm:"column:minLength;comment:可压缩最小值" json:"minLength"`             // 可压缩最小值
	MaxLength string `gorm:"column:maxLength;comment:可压缩最大值" json:"maxLength"`             // 可压缩最大值
	State     bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	Conds     string `gorm:"column:conds;comment:条件" json:"conds"`                         // 条件
}

// TableName GalloHTTPDeflatePolicy's table name
func (*GalloHTTPDeflatePolicy) TableName() string {
	return TableNameGalloHTTPDeflatePolicy
}
