// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloTrafficPackage = "galloTrafficPackages"

// GalloTrafficPackage 流量包
type GalloTrafficPackage struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Size  int32  `gorm:"column:size;comment:尺寸" json:"size"`                           // 尺寸
	Unit  string `gorm:"column:unit;comment:单位（gb|tb等）" json:"unit"`                   // 单位（gb|tb等）
	Bytes int64  `gorm:"column:bytes;comment:字节" json:"bytes"`                         // 字节
	IsOn  bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	State bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloTrafficPackage's table name
func (*GalloTrafficPackage) TableName() string {
	return TableNameGalloTrafficPackage
}
