// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerDomainHourlyStat = "galloServerDomainHourlyStats"

// GalloServerDomainHourlyStat 服务域名统计
type GalloServerDomainHourlyStat struct {
	ID                  int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	ClusterID           int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`                      // 集群ID
	NodeID              int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                            // 节点ID
	ServerID            int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                        // 服务ID
	Domain              string `gorm:"column:domain;comment:域名" json:"domain"`                              // 域名
	Hour                string `gorm:"column:hour;comment:YYYYMMDDHH" json:"hour"`                          // YYYYMMDDHH
	Bytes               int64  `gorm:"column:bytes;comment:流量" json:"bytes"`                                // 流量
	CachedBytes         int64  `gorm:"column:cachedBytes;comment:缓存流量" json:"cachedBytes"`                  // 缓存流量
	CountRequests       int64  `gorm:"column:countRequests;comment:请求数" json:"countRequests"`               // 请求数
	CountCachedRequests int64  `gorm:"column:countCachedRequests;comment:缓存请求" json:"countCachedRequests"`  // 缓存请求
	CountAttackRequests int64  `gorm:"column:countAttackRequests;comment:攻击请求数" json:"countAttackRequests"` // 攻击请求数
	AttackBytes         int64  `gorm:"column:attackBytes;comment:攻击流量" json:"attackBytes"`                  // 攻击流量
}

// TableName GalloServerDomainHourlyStat's table name
func (*GalloServerDomainHourlyStat) TableName() string {
	return TableNameGalloServerDomainHourlyStat
}
