// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloTrafficDailyStat = "galloTrafficDailyStats"

// GalloTrafficDailyStat 总的流量统计（按天）
type GalloTrafficDailyStat struct {
	ID                  int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	Day                 string `gorm:"column:day;comment:YYYYMMDD" json:"day"`                              // YYYYMMDD
	CachedBytes         int64  `gorm:"column:cachedBytes;comment:缓存流量" json:"cachedBytes"`                  // 缓存流量
	Bytes               int64  `gorm:"column:bytes;comment:流量字节" json:"bytes"`                              // 流量字节
	CountRequests       int64  `gorm:"column:countRequests;comment:请求数" json:"countRequests"`               // 请求数
	CountCachedRequests int64  `gorm:"column:countCachedRequests;comment:缓存请求数" json:"countCachedRequests"` // 缓存请求数
	CountAttackRequests int64  `gorm:"column:countAttackRequests;comment:攻击量" json:"countAttackRequests"`   // 攻击量
	AttackBytes         int64  `gorm:"column:attackBytes;comment:攻击流量" json:"attackBytes"`                  // 攻击流量
}

// TableName GalloTrafficDailyStat's table name
func (*GalloTrafficDailyStat) TableName() string {
	return TableNameGalloTrafficDailyStat
}
