// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPHeader = "galloHTTPHeaders"

// GalloHTTPHeader HTTP Header
type GalloHTTPHeader struct {
	ID              int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`  // ID
	AdminID         int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                   // 管理员ID
	UserID          int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                      // 用户ID
	TemplateID      int32  `gorm:"column:templateId;comment:模版ID" json:"templateId"`              // 模版ID
	IsOn            bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                // 是否启用
	Name            string `gorm:"column:name;comment:名称" json:"name"`                            // 名称
	Value           string `gorm:"column:value;comment:值" json:"value"`                           // 值
	Order           int32  `gorm:"column:order;comment:排序" json:"order"`                          // 排序
	Status          string `gorm:"column:status;comment:状态码设置" json:"status"`                     // 状态码设置
	DisableRedirect bool   `gorm:"column:disableRedirect;comment:是否不支持跳转" json:"disableRedirect"` // 是否不支持跳转
	ShouldAppend    bool   `gorm:"column:shouldAppend;comment:是否为附加" json:"shouldAppend"`         // 是否为附加
	ShouldReplace   bool   `gorm:"column:shouldReplace;comment:是否替换变量" json:"shouldReplace"`      // 是否替换变量
	ReplaceValues   string `gorm:"column:replaceValues;comment:替换的值" json:"replaceValues"`        // 替换的值
	Methods         string `gorm:"column:methods;comment:支持的方法" json:"methods"`                   // 支持的方法
	Domains         string `gorm:"column:domains;comment:支持的域名" json:"domains"`                   // 支持的域名
	State           bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                // 状态
	CreatedAt       int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                // 创建时间
}

// TableName GalloHTTPHeader's table name
func (*GalloHTTPHeader) TableName() string {
	return TableNameGalloHTTPHeader
}
