// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPHeaderPolicy = "galloHTTPHeaderPolicies"

// GalloHTTPHeaderPolicy Header定义
type GalloHTTPHeaderPolicy struct {
	ID                 int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`          // ID
	IsOn               bool   `gorm:"column:isOn;not null;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	State              bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                        // 状态
	AdminID            int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                           // 管理员ID
	UserID             int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                              // 用户ID
	CreatedAt          int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                        // 创建时间
	AddHeaders         string `gorm:"column:addHeaders;comment:添加的Header" json:"addHeaders"`                 // 添加的Header
	AddTrailers        string `gorm:"column:addTrailers;comment:添加的Trailers" json:"addTrailers"`             // 添加的Trailers
	SetHeaders         string `gorm:"column:setHeaders;comment:设置Header" json:"setHeaders"`                  // 设置Header
	ReplaceHeaders     string `gorm:"column:replaceHeaders;comment:替换Header内容" json:"replaceHeaders"`        // 替换Header内容
	Expires            string `gorm:"column:expires;comment:Expires单独设置" json:"expires"`                     // Expires单独设置
	DeleteHeaders      string `gorm:"column:deleteHeaders;comment:删除的Headers" json:"deleteHeaders"`          // 删除的Headers
	NonStandardHeaders string `gorm:"column:nonStandardHeaders;comment:非标Headers" json:"nonStandardHeaders"` // 非标Headers
	Cors               string `gorm:"column:cors;comment:CORS配置" json:"cors"`                                // CORS配置
}

// TableName GalloHTTPHeaderPolicy's table name
func (*GalloHTTPHeaderPolicy) TableName() string {
	return TableNameGalloHTTPHeaderPolicy
}
