// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPCacheTask = "galloHTTPCacheTasks"

// GalloHTTPCacheTask 缓存相关任务
type GalloHTTPCacheTask struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID      int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Type        string `gorm:"column:type;comment:任务类型：purge|fetch" json:"type"`             // 任务类型：purge|fetch
	KeyType     string `gorm:"column:keyType;comment:Key类型" json:"keyType"`                  // Key类型
	State       bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	CreatedAt   int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	DoneAt      int64  `gorm:"column:doneAt;comment:完成时间" json:"doneAt"`                     // 完成时间
	Day         string `gorm:"column:day;comment:创建日期YYYYMMDD" json:"day"`                   // 创建日期YYYYMMDD
	IsDone      bool   `gorm:"column:isDone;comment:是否已完成" json:"isDone"`                    // 是否已完成
	IsOk        bool   `gorm:"column:isOk;default:1;comment:是否完全成功" json:"isOk"`             // 是否完全成功
	IsReady     bool   `gorm:"column:isReady;comment:是否已准备好" json:"isReady"`                 // 是否已准备好
	Description string `gorm:"column:description;comment:描述" json:"description"`             // 描述
}

// TableName GalloHTTPCacheTask's table name
func (*GalloHTTPCacheTask) TableName() string {
	return TableNameGalloHTTPCacheTask
}
