// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloFormalClientSystem = "galloFormalClientSystems"

// GalloFormalClientSystem 终端操作系统信息
type GalloFormalClientSystem struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name   string `gorm:"column:name;comment:系统名称" json:"name"`                         // 系统名称
	Codes  string `gorm:"column:codes;comment:代号" json:"codes"`                         // 代号
	State  bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	DataID string `gorm:"column:dataId;comment:数据ID" json:"dataId"`                     // 数据ID
}

// TableName GalloFormalClientSystem's table name
func (*GalloFormalClientSystem) TableName() string {
	return TableNameGalloFormalClientSystem
}
