// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserOrderLog = "galloUserOrderLogs"

// GalloUserOrderLog 订单日志
type GalloUserOrderLog struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID   int64  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID    int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	OrderID   int64  `gorm:"column:orderId;comment:订单ID" json:"orderId"`                   // 订单ID
	Status    string `gorm:"column:status;comment:状态" json:"status"`                       // 状态
	Snapshot  string `gorm:"column:snapshot;comment:状态快照" json:"snapshot"`                 // 状态快照
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
}

// TableName GalloUserOrderLog's table name
func (*GalloUserOrderLog) TableName() string {
	return TableNameGalloUserOrderLog
}
