// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUpdatingServerList = "galloUpdatingServerLists"

// GalloUpdatingServerList 待更新服务列表
type GalloUpdatingServerList struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ClusterID int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	UniqueID  string `gorm:"column:uniqueId;comment:唯一ID" json:"uniqueId"`                 // 唯一ID
	ServerIds string `gorm:"column:serverIds;comment:服务IDs" json:"serverIds"`              // 服务IDs
	Day       string `gorm:"column:day;comment:创建日期" json:"day"`                           // 创建日期
}

// TableName GalloUpdatingServerList's table name
func (*GalloUpdatingServerList) TableName() string {
	return TableNameGalloUpdatingServerList
}
