// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeLogin = "galloNodeLogins"

// GalloNodeLogin 节点登录信息
type GalloNodeLogin struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	NodeID int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                     // 节点ID
	Role   string `gorm:"column:role;default:node;comment:角色" json:"role"`              // 角色
	Name   string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	Type   string `gorm:"column:type;comment:类型：ssh,agent" json:"type"`                 // 类型：ssh,agent
	Params string `gorm:"column:params;comment:配置参数" json:"params"`                     // 配置参数
	State  bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNodeLogin's table name
func (*GalloNodeLogin) TableName() string {
	return TableNameGalloNodeLogin
}
