// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloVersion = "galloVersions"

// GalloVersion 数据库结构版本
type GalloVersion struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Version string `gorm:"column:version" json:"version"`
}

// TableName GalloVersion's table name
func (*GalloVersion) TableName() string {
	return TableNameGalloVersion
}
