// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserAccount = "galloUserAccounts"

// GalloUserAccount 用户账号
type GalloUserAccount struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`    // ID
	UserID      int64   `gorm:"column:userId;comment:用户ID" json:"userId"`                        // 用户ID
	Total       float64 `gorm:"column:total;default:0.00;comment:可用总余额" json:"total"`            // 可用总余额
	TotalFrozen float64 `gorm:"column:totalFrozen;default:0.00;comment:冻结余额" json:"totalFrozen"` // 冻结余额
}

// TableName GalloUserAccount's table name
func (*GalloUserAccount) TableName() string {
	return TableNameGalloUserAccount
}
