// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserTrafficPackage = "galloUserTrafficPackages"

// GalloUserTrafficPackage 用户购买的流量包
type GalloUserTrafficPackage struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID     int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID      int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	PackageID   int32  `gorm:"column:packageId;comment:流量包ID" json:"packageId"`              // 流量包ID
	TotalBytes  int64  `gorm:"column:totalBytes;comment:总字节数" json:"totalBytes"`             // 总字节数
	UsedBytes   int64  `gorm:"column:usedBytes;comment:已使用字节数" json:"usedBytes"`             // 已使用字节数
	RegionID    int32  `gorm:"column:regionId;comment:区域ID" json:"regionId"`                 // 区域ID
	PeriodID    int32  `gorm:"column:periodId;comment:有效期ID" json:"periodId"`                // 有效期ID
	PeriodCount int32  `gorm:"column:periodCount;comment:有效期数量" json:"periodCount"`          // 有效期数量
	PeriodUnit  string `gorm:"column:periodUnit;comment:有效期单位" json:"periodUnit"`            // 有效期单位
	DayFrom     string `gorm:"column:dayFrom;comment:开始日期" json:"dayFrom"`                   // 开始日期
	DayTo       string `gorm:"column:dayTo;comment:结束日期" json:"dayTo"`                       // 结束日期
	CreatedAt   int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	State       bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloUserTrafficPackage's table name
func (*GalloUserTrafficPackage) TableName() string {
	return TableNameGalloUserTrafficPackage
}
