// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeIPAddressGroup = "galloNodeIPAddressGroups"

// GalloNodeIPAddressGroup IP地址分组
type GalloNodeIPAddressGroup struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name  string `gorm:"column:name;comment:分组名" json:"name"`                          // 分组名
	Value string `gorm:"column:value;comment:IP值" json:"value"`                        // IP值
}

// TableName GalloNodeIPAddressGroup's table name
func (*GalloNodeIPAddressGroup) TableName() string {
	return TableNameGalloNodeIPAddressGroup
}
