// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloSysLocker = "galloSysLockers"

// GalloSysLocker 并发锁
type GalloSysLocker struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Key       string `gorm:"column:key;comment:键值" json:"key"`                             // 键值
	Version   int64  `gorm:"column:version;comment:版本号" json:"version"`                    // 版本号
	TimeoutAt int64  `gorm:"column:timeoutAt;comment:超时时间" json:"timeoutAt"`               // 超时时间
}

// TableName GalloSysLocker's table name
func (*GalloSysLocker) TableName() string {
	return TableNameGalloSysLocker
}
