// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSRecordHourlyStat = "galloNSRecordHourlyStats"

// GalloNSRecordHourlyStat NS记录统计
type GalloNSRecordHourlyStat struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ClusterID     int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	NodeID        int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                     // 节点ID
	DomainID      int64  `gorm:"column:domainId;comment:域名ID" json:"domainId"`                 // 域名ID
	RecordID      int64  `gorm:"column:recordId;comment:记录ID" json:"recordId"`                 // 记录ID
	Day           string `gorm:"column:day;comment:YYYYMMDD" json:"day"`                       // YYYYMMDD
	Hour          string `gorm:"column:hour;comment:YYYYMMDDHH" json:"hour"`                   // YYYYMMDDHH
	CountRequests int64  `gorm:"column:countRequests;comment:请求数" json:"countRequests"`        // 请求数
	Bytes         int64  `gorm:"column:bytes;comment:流量" json:"bytes"`                         // 流量
}

// TableName GalloNSRecordHourlyStat's table name
func (*GalloNSRecordHourlyStat) TableName() string {
	return TableNameGalloNSRecordHourlyStat
}
