// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloMessageRecipientGroup = "galloMessageRecipientGroups"

// GalloMessageRecipientGroup 消息接收人分组
type GalloMessageRecipientGroup struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name  string `gorm:"column:name;comment:分组名" json:"name"`                          // 分组名
	Order int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	IsOn  bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	State bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloMessageRecipientGroup's table name
func (*GalloMessageRecipientGroup) TableName() string {
	return TableNameGalloMessageRecipientGroup
}
