// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloSSLCertGroup = "galloSSLCertGroups"

// GalloSSLCertGroup 证书分组
type GalloSSLCertGroup struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID   int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID    int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Name      string `gorm:"column:name;comment:分组名" json:"name"`                          // 分组名
	Order     int32  `gorm:"column:order;comment:分组排序" json:"order"`                       // 分组排序
	State     bool   `gorm:"column:state;comment:状态" json:"state"`                         // 状态
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
}

// TableName GalloSSLCertGroup's table name
func (*GalloSSLCertGroup) TableName() string {
	return TableNameGalloSSLCertGroup
}
