// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSAccessLog = "galloNSAccessLogs"

// GalloNSAccessLog 域名服务访问日志
type GalloNSAccessLog struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	NodeID     int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                     // 节点ID
	DomainID   int32  `gorm:"column:domainId;comment:域名ID" json:"domainId"`                 // 域名ID
	RecordID   int32  `gorm:"column:recordId;comment:记录ID" json:"recordId"`                 // 记录ID
	Content    string `gorm:"column:content;comment:访问数据" json:"content"`                   // 访问数据
	RequestID  string `gorm:"column:requestId;comment:请求ID" json:"requestId"`               // 请求ID
	CreatedAt  int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	RemoteAddr string `gorm:"column:remoteAddr;comment:IP" json:"remoteAddr"`               // IP
}

// TableName GalloNSAccessLog's table name
func (*GalloNSAccessLog) TableName() string {
	return TableNameGalloNSAccessLog
}
