// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloTrafficPackagePrice = "galloTrafficPackagePrices"

// GalloTrafficPackagePrice 流量包价格
type GalloTrafficPackagePrice struct {
	ID            int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`        // ID
	PackageID     int32   `gorm:"column:packageId;comment:套餐ID" json:"packageId"`                      // 套餐ID
	RegionID      int32   `gorm:"column:regionId;comment:区域ID" json:"regionId"`                        // 区域ID
	PeriodID      int32   `gorm:"column:periodId;comment:有效期ID" json:"periodId"`                       // 有效期ID
	Price         float64 `gorm:"column:price;default:0.00;comment:价格" json:"price"`                   // 价格
	DiscountPrice float64 `gorm:"column:discountPrice;default:0.00;comment:折后价格" json:"discountPrice"` // 折后价格
}

// TableName GalloTrafficPackagePrice's table name
func (*GalloTrafficPackagePrice) TableName() string {
	return TableNameGalloTrafficPackagePrice
}
