// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserBill = "galloUserBills"

// GalloUserBill 用户账单
type GalloUserBill struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`       // ID
	UserID      int32   `gorm:"column:userId;comment:用户ID" json:"userId"`                           // 用户ID
	Type        string  `gorm:"column:type;comment:消费类型" json:"type"`                               // 消费类型
	PricePeriod string  `gorm:"column:pricePeriod;default:monthly;comment:计费周期" json:"pricePeriod"` // 计费周期
	Description string  `gorm:"column:description;comment:描述" json:"description"`                   // 描述
	Amount      float64 `gorm:"column:amount;default:0.00;comment:消费数额" json:"amount"`              // 消费数额
	DayFrom     string  `gorm:"column:dayFrom;comment:YYYYMMDD" json:"dayFrom"`                     // YYYYMMDD
	DayTo       string  `gorm:"column:dayTo;comment:YYYYMMDD" json:"dayTo"`                         // YYYYMMDD
	Month       string  `gorm:"column:month;comment:帐期YYYYMM" json:"month"`                         // 帐期YYYYMM
	CanPay      bool    `gorm:"column:canPay;default:1;comment:是否可以支付" json:"canPay"`               // 是否可以支付
	IsPaid      bool    `gorm:"column:isPaid;comment:是否已支付" json:"isPaid"`                          // 是否已支付
	PaidAt      int64   `gorm:"column:paidAt;comment:支付时间" json:"paidAt"`                           // 支付时间
	Code        string  `gorm:"column:code;comment:账单编号" json:"code"`                               // 账单编号
	CreatedAt   int64   `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                     // 创建时间
	CreatedDay  string  `gorm:"column:createdDay;comment:创建日期" json:"createdDay"`                   // 创建日期
	State       bool    `gorm:"column:state;default:1;comment:状态" json:"state"`                     // 状态
}

// TableName GalloUserBill's table name
func (*GalloUserBill) TableName() string {
	return TableNameGalloUserBill
}
