// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeIPAddressLog = "galloNodeIPAddressLogs"

// GalloNodeIPAddressLog IP状态变更日志
type GalloNodeIPAddressLog struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AddressID   int64  `gorm:"column:addressId;comment:地址ID" json:"addressId"`               // 地址ID
	AdminID     int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	Description string `gorm:"column:description;comment:描述" json:"description"`             // 描述
	CreatedAt   int64  `gorm:"column:createdAt;comment:操作时间" json:"createdAt"`               // 操作时间
	IsUp        bool   `gorm:"column:isUp;comment:是否在线" json:"isUp"`                         // 是否在线
	IsOn        bool   `gorm:"column:isOn;comment:是否启用" json:"isOn"`                         // 是否启用
	CanAccess   bool   `gorm:"column:canAccess;comment:是否可访问" json:"canAccess"`              // 是否可访问
	Day         string `gorm:"column:day;comment:YYYYMMDD，用来清理" json:"day"`                  // YYYYMMDD，用来清理
	BackupIP    string `gorm:"column:backupIP;comment:备用IP" json:"backupIP"`                 // 备用IP
}

// TableName GalloNodeIPAddressLog's table name
func (*GalloNodeIPAddressLog) TableName() string {
	return TableNameGalloNodeIPAddressLog
}
