// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeClusterFirewallAction = "galloNodeClusterFirewallActions"

// GalloNodeClusterFirewallAction 防火墙动作
type GalloNodeClusterFirewallAction struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID    int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	ClusterID  int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	Name       string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	EventLevel string `gorm:"column:eventLevel;comment:级别" json:"eventLevel"`               // 级别
	Type       string `gorm:"column:type;comment:动作类型" json:"type"`                         // 动作类型
	Params     string `gorm:"column:params;comment:参数" json:"params"`                       // 参数
	State      bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNodeClusterFirewallAction's table name
func (*GalloNodeClusterFirewallAction) TableName() string {
	return TableNameGalloNodeClusterFirewallAction
}
