// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerClientSystemMonthlyStat = "galloServerClientSystemMonthlyStats"

// GalloServerClientSystemMonthlyStat 操作系统统计（按月）
type GalloServerClientSystemMonthlyStat struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ServerID int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                 // 服务ID
	SystemID int32  `gorm:"column:systemId;comment:系统ID" json:"systemId"`                 // 系统ID
	Version  string `gorm:"column:version;comment:主版本号" json:"version"`                   // 主版本号
	Month    string `gorm:"column:month;comment:YYYYMM" json:"month"`                     // YYYYMM
	Count    int64  `gorm:"column:count;comment:数量" json:"count"`                         // 数量
}

// TableName GalloServerClientSystemMonthlyStat's table name
func (*GalloServerClientSystemMonthlyStat) TableName() string {
	return TableNameGalloServerClientSystemMonthlyStat
}
