// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserPlanStat = "galloUserPlanStats"

// GalloUserPlanStat 用户套餐统计
type GalloUserPlanStat struct {
	ID                        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                           // ID
	UserPlanID                int64  `gorm:"column:userPlanId;comment:用户套餐ID" json:"userPlanId"`                                     // 用户套餐ID
	Date                      string `gorm:"column:date;comment:日期：YYYYMMDD或YYYYMM" json:"date"`                                     // 日期：YYYYMMDD或YYYYMM
	DateType                  string `gorm:"column:dateType;comment:日期类型：day|month" json:"dateType"`                                 // 日期类型：day|month
	TrafficBytes              int64  `gorm:"column:trafficBytes;comment:流量" json:"trafficBytes"`                                     // 流量
	CountRequests             int64  `gorm:"column:countRequests;comment:总请求数" json:"countRequests"`                                 // 总请求数
	CountWebsocketConnections int64  `gorm:"column:countWebsocketConnections;comment:Websocket连接数" json:"countWebsocketConnections"` // Websocket连接数
	IsProcessed               bool   `gorm:"column:isProcessed;comment:是否已处理" json:"isProcessed"`                                    // 是否已处理
}

// TableName GalloUserPlanStat's table name
func (*GalloUserPlanStat) TableName() string {
	return TableNameGalloUserPlanStat
}
