// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeTrafficHourlyStat = "galloNodeTrafficHourlyStats"

// GalloNodeTrafficHourlyStat 总的流量统计（按天）
type GalloNodeTrafficHourlyStat struct {
	ID                  int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`         // ID
	Role                string `gorm:"column:role;default:node;comment:节点角色" json:"role"`                    // 节点角色
	ClusterID           int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`                       // 集群ID
	NodeID              int32  `gorm:"column:nodeId;comment:集群ID" json:"nodeId"`                             // 集群ID
	Hour                string `gorm:"column:hour;comment:YYYYMMDDHH" json:"hour"`                           // YYYYMMDDHH
	Bytes               int64  `gorm:"column:bytes;comment:流量字节" json:"bytes"`                               // 流量字节
	CachedBytes         int64  `gorm:"column:cachedBytes;comment:缓存流量" json:"cachedBytes"`                   // 缓存流量
	CountRequests       int64  `gorm:"column:countRequests;comment:请求数" json:"countRequests"`                // 请求数
	CountCachedRequests int64  `gorm:"column:countCachedRequests;comment:缓存的请求数" json:"countCachedRequests"` // 缓存的请求数
	CountAttackRequests int64  `gorm:"column:countAttackRequests;comment:攻击请求数" json:"countAttackRequests"`  // 攻击请求数
	AttackBytes         int64  `gorm:"column:attackBytes;comment:攻击流量" json:"attackBytes"`                   // 攻击流量
}

// TableName GalloNodeTrafficHourlyStat's table name
func (*GalloNodeTrafficHourlyStat) TableName() string {
	return TableNameGalloNodeTrafficHourlyStat
}
