// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSRouteCategory = "galloNSRouteCategories"

// GalloNSRouteCategory 线路分类
type GalloNSRouteCategory struct {
	ID      int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	IsOn    bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Name    string `gorm:"column:name;comment:分类名" json:"name"`                          // 分类名
	AdminID int64  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID  int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Order   int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	State   bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNSRouteCategory's table name
func (*GalloNSRouteCategory) TableName() string {
	return TableNameGalloNSRouteCategory
}
