// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPRewriteRule = "galloHTTPRewriteRules"

// GalloHTTPRewriteRule 重写规则
type GalloHTTPRewriteRule struct {
	ID             int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`  // ID
	AdminID        int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                   // 管理员ID
	UserID         int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                      // 用户ID
	TemplateID     int32  `gorm:"column:templateId;comment:模版ID" json:"templateId"`              // 模版ID
	IsOn           bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                // 是否启用
	State          bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                // 状态
	CreatedAt      int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                // 创建时间
	Pattern        string `gorm:"column:pattern;comment:匹配规则" json:"pattern"`                    // 匹配规则
	Replace        string `gorm:"column:replace;comment:跳转后的地址" json:"replace"`                  // 跳转后的地址
	Mode           string `gorm:"column:mode;comment:替换模式" json:"mode"`                          // 替换模式
	RedirectStatus int32  `gorm:"column:redirectStatus;comment:跳转的状态码" json:"redirectStatus"`    // 跳转的状态码
	ProxyHost      string `gorm:"column:proxyHost;comment:代理的主机名" json:"proxyHost"`              // 代理的主机名
	IsBreak        bool   `gorm:"column:isBreak;default:1;comment:是否终止解析" json:"isBreak"`        // 是否终止解析
	WithQuery      bool   `gorm:"column:withQuery;default:1;comment:是否保留URI参数" json:"withQuery"` // 是否保留URI参数
	Conds          string `gorm:"column:conds;comment:匹配条件" json:"conds"`                        // 匹配条件
}

// TableName GalloHTTPRewriteRule's table name
func (*GalloHTTPRewriteRule) TableName() string {
	return TableNameGalloHTTPRewriteRule
}
