// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUser = "galloUsers"

// GalloUser 用户
type GalloUser struct {
	ID                int32   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`              // ID
	IsOn              bool    `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                            // 是否启用
	Username          string  `gorm:"column:username;comment:用户名" json:"username"`                               // 用户名
	Password          string  `gorm:"column:password;comment:密码" json:"password"`                                // 密码
	Fullname          string  `gorm:"column:fullname;comment:真实姓名" json:"fullname"`                              // 真实姓名
	Mobile            string  `gorm:"column:mobile;comment:手机号" json:"mobile"`                                   // 手机号
	VerifiedMobile    string  `gorm:"column:verifiedMobile;comment:已验证手机号" json:"verifiedMobile"`                // 已验证手机号
	MobileIsVerified  bool    `gorm:"column:mobileIsVerified;comment:手机号是否已验证" json:"mobileIsVerified"`          // 手机号是否已验证
	Tel               string  `gorm:"column:tel;comment:联系电话" json:"tel"`                                        // 联系电话
	Remark            string  `gorm:"column:remark;comment:备注" json:"remark"`                                    // 备注
	Email             string  `gorm:"column:email;comment:邮箱地址" json:"email"`                                    // 邮箱地址
	VerifiedEmail     string  `gorm:"column:verifiedEmail;comment:激活后的邮箱" json:"verifiedEmail"`                  // 激活后的邮箱
	EmailIsVerified   bool    `gorm:"column:emailIsVerified;comment:邮箱是否已验证" json:"emailIsVerified"`             // 邮箱是否已验证
	AvatarFileID      int64   `gorm:"column:avatarFileId;comment:头像文件ID" json:"avatarFileId"`                    // 头像文件ID
	CreatedAt         int64   `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                            // 创建时间
	Day               string  `gorm:"column:day;comment:YYYYMMDD" json:"day"`                                    // YYYYMMDD
	UpdatedAt         int64   `gorm:"column:updatedAt;comment:修改时间" json:"updatedAt"`                            // 修改时间
	State             bool    `gorm:"column:state;default:1;comment:状态" json:"state"`                            // 状态
	Source            string  `gorm:"column:source;comment:来源" json:"source"`                                    // 来源
	ClusterID         int32   `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`                            // 集群ID
	Features          string  `gorm:"column:features;comment:允许操作的特征" json:"features"`                           // 允许操作的特征
	RegisteredIP      string  `gorm:"column:registeredIP;comment:注册使用的IP" json:"registeredIP"`                   // 注册使用的IP
	IsRejected        bool    `gorm:"column:isRejected;comment:是否已拒绝" json:"isRejected"`                         // 是否已拒绝
	RejectReason      string  `gorm:"column:rejectReason;comment:拒绝理由" json:"rejectReason"`                      // 拒绝理由
	IsVerified        bool    `gorm:"column:isVerified;default:1;comment:是否验证通过" json:"isVerified"`              // 是否验证通过
	RequirePlans      bool    `gorm:"column:requirePlans;comment:是否需要购买套餐" json:"requirePlans"`                  // 是否需要购买套餐
	Modules           string  `gorm:"column:modules;comment:用户模块" json:"modules"`                                // 用户模块
	PriceType         string  `gorm:"column:priceType;comment:计费类型：traffic|bandwidth" json:"priceType"`          // 计费类型：traffic|bandwidth
	PricePeriod       string  `gorm:"column:pricePeriod;comment:结算周期" json:"pricePeriod"`                        // 结算周期
	ServersEnabled    bool    `gorm:"column:serversEnabled;default:1;comment:是否禁用所有服务" json:"serversEnabled"`    // 是否禁用所有服务
	Notification      string  `gorm:"column:notification;comment:通知设置" json:"notification"`                      // 通知设置
	BandwidthAlgo     string  `gorm:"column:bandwidthAlgo;comment:带宽算法" json:"bandwidthAlgo"`                    // 带宽算法
	BandwidthModifier float64 `gorm:"column:bandwidthModifier;default:0;comment:带宽修正值" json:"bandwidthModifier"` // 带宽修正值
	Lang              string  `gorm:"column:lang;comment:语言代号" json:"lang"`                                      // 语言代号
}

// TableName GalloUser's table name
func (*GalloUser) TableName() string {
	return TableNameGalloUser
}
