// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerStatBoard = "galloServerStatBoards"

// GalloServerStatBoard 服务统计看板
type GalloServerStatBoard struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name      string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	ClusterID int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	IsOn      bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Order     int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	State     bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloServerStatBoard's table name
func (*GalloServerStatBoard) TableName() string {
	return TableNameGalloServerStatBoard
}
