// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerBandwidthStat = "galloServerBandwidthStats"

// GalloServerBandwidthStat 服务峰值带宽统计
type GalloServerBandwidthStat struct {
	ID                  int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`         // ID
	UserID              int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                             // 用户ID
	ServerID            int64  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                         // 服务ID
	RegionID            int32  `gorm:"column:regionId;comment:区域ID" json:"regionId"`                         // 区域ID
	UserPlanID          int64  `gorm:"column:userPlanId;comment:用户套餐ID" json:"userPlanId"`                   // 用户套餐ID
	Day                 string `gorm:"column:day;comment:日期YYYYMMDD" json:"day"`                             // 日期YYYYMMDD
	TimeAt              string `gorm:"column:timeAt;comment:时间点HHMM" json:"timeAt"`                          // 时间点HHMM
	Bytes               int64  `gorm:"column:bytes;comment:带宽字节" json:"bytes"`                               // 带宽字节
	AvgBytes            int64  `gorm:"column:avgBytes;comment:平均流量" json:"avgBytes"`                         // 平均流量
	CachedBytes         int64  `gorm:"column:cachedBytes;comment:缓存的流量" json:"cachedBytes"`                  // 缓存的流量
	AttackBytes         int64  `gorm:"column:attackBytes;comment:攻击流量" json:"attackBytes"`                   // 攻击流量
	CountRequests       int64  `gorm:"column:countRequests;comment:请求数" json:"countRequests"`                // 请求数
	CountCachedRequests int64  `gorm:"column:countCachedRequests;comment:缓存的请求数" json:"countCachedRequests"` // 缓存的请求数
	CountAttackRequests int64  `gorm:"column:countAttackRequests;comment:攻击请求数" json:"countAttackRequests"`  // 攻击请求数
	TotalBytes          int64  `gorm:"column:totalBytes;comment:总流量" json:"totalBytes"`                      // 总流量
}

// TableName GalloServerBandwidthStat's table name
func (*GalloServerBandwidthStat) TableName() string {
	return TableNameGalloServerBandwidthStat
}
