// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeClusterMetricItem = "galloNodeClusterMetricItems"

// GalloNodeClusterMetricItem 集群使用的指标
type GalloNodeClusterMetricItem struct {
	ID        int32 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	IsOn      bool  `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	ClusterID int32 `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	ItemID    int64 `gorm:"column:itemId;comment:指标ID" json:"itemId"`                     // 指标ID
	State     bool  `gorm:"column:state;default:1;comment:是否启用" json:"state"`             // 是否启用
}

// TableName GalloNodeClusterMetricItem's table name
func (*GalloNodeClusterMetricItem) TableName() string {
	return TableNameGalloNodeClusterMetricItem
}
