// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloLog = "galloLogs"

// GalloLog 操作日志
type GalloLog struct {
	ID              int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`  // ID
	Level           string `gorm:"column:level;comment:级别" json:"level"`                          // 级别
	Description     string `gorm:"column:description;comment:描述" json:"description"`              // 描述
	CreatedAt       int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                // 创建时间
	Action          string `gorm:"column:action;comment:动作" json:"action"`                        // 动作
	UserID          int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                      // 用户ID
	AdminID         int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                   // 管理员ID
	ProviderID      int32  `gorm:"column:providerId;comment:供应商ID" json:"providerId"`             // 供应商ID
	IP              string `gorm:"column:ip;comment:IP地址" json:"ip"`                              // IP地址
	Type            string `gorm:"column:type;default:admin;comment:类型：admin, user" json:"type"`  // 类型：admin, user
	Day             string `gorm:"column:day;comment:日期" json:"day"`                              // 日期
	BillID          int32  `gorm:"column:billId;comment:账单ID" json:"billId"`                      // 账单ID
	LangMessageCode string `gorm:"column:langMessageCode;comment:多语言消息代号" json:"langMessageCode"` // 多语言消息代号
	LangMessageArgs string `gorm:"column:langMessageArgs;comment:多语言参数" json:"langMessageArgs"`   // 多语言参数
	Params          string `gorm:"column:params;comment:关联对象参数" json:"params"`                    // 关联对象参数
}

// TableName GalloLog's table name
func (*GalloLog) TableName() string {
	return TableNameGalloLog
}
