// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNode = "galloNodes"

// GalloNode 节点
type GalloNode struct {
	ID                     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`               // ID
	AdminID                int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                                // 管理员ID
	UserID                 int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                                   // 用户ID
	Level                  bool   `gorm:"column:level;default:1;comment:级别" json:"level"`                             // 级别
	LnAddrs                string `gorm:"column:lnAddrs;comment:Ln级别访问地址" json:"lnAddrs"`                             // Ln级别访问地址
	IsOn                   bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                             // 是否启用
	IsUp                   bool   `gorm:"column:isUp;default:1;comment:是否在线" json:"isUp"`                             // 是否在线
	CountUp                int32  `gorm:"column:countUp;comment:连续在线次数" json:"countUp"`                               // 连续在线次数
	CountDown              int32  `gorm:"column:countDown;comment:连续下线次数" json:"countDown"`                           // 连续下线次数
	IsActive               bool   `gorm:"column:isActive;default:1;comment:是否活跃" json:"isActive"`                     // 是否活跃
	InactiveNotifiedAt     int64  `gorm:"column:inactiveNotifiedAt;comment:离线通知时间" json:"inactiveNotifiedAt"`         // 离线通知时间
	UniqueID               string `gorm:"column:uniqueId;comment:节点ID" json:"uniqueId"`                               // 节点ID
	Secret                 string `gorm:"column:secret;comment:密钥" json:"secret"`                                     // 密钥
	Name                   string `gorm:"column:name;comment:节点名" json:"name"`                                        // 节点名
	Code                   string `gorm:"column:code;comment:代号" json:"code"`                                         // 代号
	ClusterID              int32  `gorm:"column:clusterId;comment:主集群ID" json:"clusterId"`                            // 主集群ID
	SecondaryClusterIds    string `gorm:"column:secondaryClusterIds;comment:从集群ID" json:"secondaryClusterIds"`        // 从集群ID
	RegionID               int32  `gorm:"column:regionId;comment:区域ID" json:"regionId"`                               // 区域ID
	GroupID                int32  `gorm:"column:groupId;comment:分组ID" json:"groupId"`                                 // 分组ID
	CreatedAt              int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                             // 创建时间
	Status                 string `gorm:"column:status;comment:最新的状态" json:"status"`                                  // 最新的状态
	Version                int32  `gorm:"column:version;comment:当前版本号" json:"version"`                                // 当前版本号
	LatestVersion          int32  `gorm:"column:latestVersion;comment:最后版本号" json:"latestVersion"`                    // 最后版本号
	InstallDir             string `gorm:"column:installDir;comment:安装目录" json:"installDir"`                           // 安装目录
	IsInstalled            bool   `gorm:"column:isInstalled;comment:是否已安装" json:"isInstalled"`                        // 是否已安装
	InstallStatus          string `gorm:"column:installStatus;comment:安装状态" json:"installStatus"`                     // 安装状态
	State                  bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                             // 状态
	ConnectedAPINodes      string `gorm:"column:connectedAPINodes;comment:当前连接的API节点" json:"connectedAPINodes"`       // 当前连接的API节点
	MaxCPU                 int32  `gorm:"column:maxCPU;comment:可以使用的最多CPU" json:"maxCPU"`                             // 可以使用的最多CPU
	MaxThreads             int32  `gorm:"column:maxThreads;comment:最大线程数" json:"maxThreads"`                          // 最大线程数
	DdosProtection         string `gorm:"column:ddosProtection;comment:DDOS配置" json:"ddosProtection"`                 // DDOS配置
	DNSRoutes              string `gorm:"column:dnsRoutes;comment:DNS线路设置" json:"dnsRoutes"`                          // DNS线路设置
	MaxCacheDiskCapacity   string `gorm:"column:maxCacheDiskCapacity;comment:硬盘缓存容量" json:"maxCacheDiskCapacity"`     // 硬盘缓存容量
	MaxCacheMemoryCapacity string `gorm:"column:maxCacheMemoryCapacity;comment:内存缓存容量" json:"maxCacheMemoryCapacity"` // 内存缓存容量
	CacheDiskDir           string `gorm:"column:cacheDiskDir;comment:主缓存目录" json:"cacheDiskDir"`                      // 主缓存目录
	CacheDiskSubDirs       string `gorm:"column:cacheDiskSubDirs;comment:其他缓存目录" json:"cacheDiskSubDirs"`             // 其他缓存目录
	DNSResolver            string `gorm:"column:dnsResolver;comment:DNS解析器" json:"dnsResolver"`                       // DNS解析器
	EnableIPLists          bool   `gorm:"column:enableIPLists;default:1;comment:启用IP名单" json:"enableIPLists"`         // 启用IP名单
	APINodeAddrs           string `gorm:"column:apiNodeAddrs;comment:API节点地址" json:"apiNodeAddrs"`                    // API节点地址
	OfflineDay             string `gorm:"column:offlineDay;comment:下线日期YYYYMMDD" json:"offlineDay"`                   // 下线日期YYYYMMDD
	OfflineIsNotified      bool   `gorm:"column:offlineIsNotified;comment:下线是否已通知" json:"offlineIsNotified"`          // 下线是否已通知
	IsBackupForCluster     bool   `gorm:"column:isBackupForCluster;comment:是否为集群备用节点" json:"isBackupForCluster"`      // 是否为集群备用节点
	IsBackupForGroup       bool   `gorm:"column:isBackupForGroup;comment:是否为分组备用节点" json:"isBackupForGroup"`          // 是否为分组备用节点
	BackupIPs              string `gorm:"column:backupIPs;comment:备用IP" json:"backupIPs"`                             // 备用IP
	ActionStatus           string `gorm:"column:actionStatus;comment:当前动作配置" json:"actionStatus"`                     // 当前动作配置
}

// TableName GalloNode's table name
func (*GalloNode) TableName() string {
	return TableNameGalloNode
}
