// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloFile = "galloFiles"

// GalloFile 文件管理
type GalloFile struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID     int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	Code        string `gorm:"column:code;comment:代号" json:"code"`                           // 代号
	UserID      int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Description string `gorm:"column:description;comment:文件描述" json:"description"`           // 文件描述
	Filename    string `gorm:"column:filename;comment:文件名" json:"filename"`                  // 文件名
	Size        int32  `gorm:"column:size;comment:文件尺寸" json:"size"`                         // 文件尺寸
	MimeType    string `gorm:"column:mimeType;comment:Mime类型" json:"mimeType"`               // Mime类型
	CreatedAt   int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	Order       int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	Type        string `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	State       bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	IsFinished  bool   `gorm:"column:isFinished;comment:是否已完成上传" json:"isFinished"`          // 是否已完成上传
	IsPublic    bool   `gorm:"column:isPublic;comment:是否可以公开访问" json:"isPublic"`             // 是否可以公开访问
}

// TableName GalloFile's table name
func (*GalloFile) TableName() string {
	return TableNameGalloFile
}
