// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloPostCategory = "galloPostCategories"

// GalloPostCategory 文章分类
type GalloPostCategory struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name  string `gorm:"column:name;comment:分类名称" json:"name"`                         // 分类名称
	IsOn  bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Code  string `gorm:"column:code;comment:代号" json:"code"`                           // 代号
	Order int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	State bool   `gorm:"column:state;default:1;comment:分类状态" json:"state"`             // 分类状态
}

// TableName GalloPostCategory's table name
func (*GalloPostCategory) TableName() string {
	return TableNameGalloPostCategory
}
