// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloSysEvent = "galloSysEvents"

// GalloSysEvent 系统事件
type GalloSysEvent struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Type      string `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	Params    string `gorm:"column:params;comment:参数" json:"params"`                       // 参数
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
}

// TableName GalloSysEvent's table name
func (*GalloSysEvent) TableName() string {
	return TableNameGalloSysEvent
}
