// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloIPLibraryArtifact = "galloIPLibraryArtifacts"

// GalloIPLibraryArtifact IP库制品
type GalloIPLibraryArtifact struct {
	ID            int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name          string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	FileID        int64  `gorm:"column:fileId;comment:文件ID" json:"fileId"`                     // 文件ID
	LibraryFileID int32  `gorm:"column:libraryFileId;comment:IP库文件ID" json:"libraryFileId"`    // IP库文件ID
	CreatedAt     int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	Meta          string `gorm:"column:meta;comment:元数据" json:"meta"`                          // 元数据
	IsPublic      bool   `gorm:"column:isPublic;comment:是否为公用" json:"isPublic"`                // 是否为公用
	Code          string `gorm:"column:code;comment:代号" json:"code"`                           // 代号
	State         bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloIPLibraryArtifact's table name
func (*GalloIPLibraryArtifact) TableName() string {
	return TableNameGalloIPLibraryArtifact
}
