// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPCachePolicy = "galloHTTPCachePolicies"

// GalloHTTPCachePolicy HTTP缓存策略
type GalloHTTPCachePolicy struct {
	ID                   int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`               // ID
	AdminID              int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                                // 管理员ID
	UserID               int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                                   // 用户ID
	TemplateID           int32  `gorm:"column:templateId;comment:模版ID" json:"templateId"`                           // 模版ID
	IsOn                 bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                             // 是否启用
	Name                 string `gorm:"column:name;comment:名称" json:"name"`                                         // 名称
	Capacity             string `gorm:"column:capacity;comment:容量数据" json:"capacity"`                               // 容量数据
	MaxKeys              int64  `gorm:"column:maxKeys;comment:最多Key值" json:"maxKeys"`                               // 最多Key值
	MaxSize              string `gorm:"column:maxSize;comment:最大缓存内容尺寸" json:"maxSize"`                             // 最大缓存内容尺寸
	Type                 string `gorm:"column:type;comment:存储类型" json:"type"`                                       // 存储类型
	Options              string `gorm:"column:options;comment:存储选项" json:"options"`                                 // 存储选项
	CreatedAt            int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                             // 创建时间
	State                bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                             // 状态
	Description          string `gorm:"column:description;comment:描述" json:"description"`                           // 描述
	Refs                 string `gorm:"column:refs;comment:默认的缓存设置" json:"refs"`                                    // 默认的缓存设置
	SyncCompressionCache bool   `gorm:"column:syncCompressionCache;comment:是否同步写入压缩缓存" json:"syncCompressionCache"` // 是否同步写入压缩缓存
	FetchTimeout         string `gorm:"column:fetchTimeout;comment:预热超时时间" json:"fetchTimeout"`                     // 预热超时时间
}

// TableName GalloHTTPCachePolicy's table name
func (*GalloHTTPCachePolicy) TableName() string {
	return TableNameGalloHTTPCachePolicy
}
