// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPLocation = "galloHTTPLocations"

// GalloHTTPLocation 路由规则配置
type GalloHTTPLocation struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	TemplateID   int32  `gorm:"column:templateId;comment:模版ID" json:"templateId"`             // 模版ID
	AdminID      int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID       int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	ParentID     int32  `gorm:"column:parentId;comment:父级ID" json:"parentId"`                 // 父级ID
	State        bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	CreatedAt    int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	Pattern      string `gorm:"column:pattern;comment:匹配规则" json:"pattern"`                   // 匹配规则
	IsOn         bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Name         string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	Description  string `gorm:"column:description;comment:描述" json:"description"`             // 描述
	WebID        int32  `gorm:"column:webId;comment:Web配置ID" json:"webId"`                    // Web配置ID
	ReverseProxy string `gorm:"column:reverseProxy;comment:反向代理" json:"reverseProxy"`         // 反向代理
	URLPrefix    string `gorm:"column:urlPrefix;comment:URL前缀" json:"urlPrefix"`              // URL前缀
	IsBreak      bool   `gorm:"column:isBreak;comment:是否终止匹配" json:"isBreak"`                 // 是否终止匹配
	Conds        string `gorm:"column:conds;comment:匹配条件" json:"conds"`                       // 匹配条件
	Domains      string `gorm:"column:domains;comment:专属域名" json:"domains"`                   // 专属域名
}

// TableName GalloHTTPLocation's table name
func (*GalloHTTPLocation) TableName() string {
	return TableNameGalloHTTPLocation
}
