// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloScriptHistory = "galloScriptHistories"

// GalloScriptHistory 脚本历史记录
type GalloScriptHistory struct {
	ID       int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID   int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	ScriptID int64  `gorm:"column:scriptId;comment:脚本ID" json:"scriptId"`                 // 脚本ID
	Filename string `gorm:"column:filename;comment:文件名" json:"filename"`                  // 文件名
	Code     string `gorm:"column:code;comment:代码" json:"code"`                           // 代码
	Version  int64  `gorm:"column:version;comment:版本号" json:"version"`                    // 版本号
}

// TableName GalloScriptHistory's table name
func (*GalloScriptHistory) TableName() string {
	return TableNameGalloScriptHistory
}
