// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserTicket = "galloUserTickets"

// GalloUserTicket 工单
type GalloUserTicket struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	CategoryID int64  `gorm:"column:categoryId;comment:分类ID" json:"categoryId"`             // 分类ID
	ToAdminID  int64  `gorm:"column:toAdminId;comment:指派的管理员ID" json:"toAdminId"`           // 指派的管理员ID
	UserID     int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Subject    string `gorm:"column:subject;comment:标题" json:"subject"`                     // 标题
	Body       string `gorm:"column:body;comment:内容" json:"body"`                           // 内容
	Status     string `gorm:"column:status;comment:状态" json:"status"`                       // 状态
	CreatedAt  int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	LastLogAt  int64  `gorm:"column:lastLogAt;comment:最后日志时间" json:"lastLogAt"`             // 最后日志时间
	State      bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloUserTicket's table name
func (*GalloUserTicket) TableName() string {
	return TableNameGalloUserTicket
}
