// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPFirewallPolicy = "galloHTTPFirewallPolicies"

// GalloHTTPFirewallPolicy HTTP防火墙
type GalloHTTPFirewallPolicy struct {
	ID                 int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                  // ID
	TemplateID         int32  `gorm:"column:templateId;comment:模版ID" json:"templateId"`                              // 模版ID
	AdminID            int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                                   // 管理员ID
	UserID             int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                                      // 用户ID
	ServerID           int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                                  // 服务ID
	GroupID            int32  `gorm:"column:groupId;comment:服务分组ID" json:"groupId"`                                  // 服务分组ID
	State              bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                                // 状态
	CreatedAt          int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                                // 创建时间
	IsOn               bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                                // 是否启用
	Name               string `gorm:"column:name;comment:名称" json:"name"`                                            // 名称
	Description        string `gorm:"column:description;comment:描述" json:"description"`                              // 描述
	Inbound            string `gorm:"column:inbound;comment:入站规则" json:"inbound"`                                    // 入站规则
	Outbound           string `gorm:"column:outbound;comment:出站规则" json:"outbound"`                                  // 出站规则
	BlockOptions       string `gorm:"column:blockOptions;comment:BLOCK动作选项" json:"blockOptions"`                     // BLOCK动作选项
	PageOptions        string `gorm:"column:pageOptions;comment:PAGE动作选项" json:"pageOptions"`                        // PAGE动作选项
	CaptchaOptions     string `gorm:"column:captchaOptions;comment:验证码动作选项" json:"captchaOptions"`                   // 验证码动作选项
	Mode               string `gorm:"column:mode;default:defend;comment:模式" json:"mode"`                             // 模式
	UseLocalFirewall   bool   `gorm:"column:useLocalFirewall;default:1;comment:是否自动使用本地防火墙" json:"useLocalFirewall"` // 是否自动使用本地防火墙
	SynFlood           string `gorm:"column:synFlood;comment:SynFlood防御设置" json:"synFlood"`                          // SynFlood防御设置
	Log                string `gorm:"column:log;comment:日志配置" json:"log"`                                            // 日志配置
	MaxRequestBodySize int32  `gorm:"column:maxRequestBodySize;comment:可以检查的最大请求内容尺寸" json:"maxRequestBodySize"`     // 可以检查的最大请求内容尺寸
	DenyCountryHTML    string `gorm:"column:denyCountryHTML;comment:区域封禁提示" json:"denyCountryHTML"`                  // 区域封禁提示
	DenyProvinceHTML   string `gorm:"column:denyProvinceHTML;comment:省份封禁提示" json:"denyProvinceHTML"`                // 省份封禁提示
}

// TableName GalloHTTPFirewallPolicy's table name
func (*GalloHTTPFirewallPolicy) TableName() string {
	return TableNameGalloHTTPFirewallPolicy
}
