// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSUserPlan = "galloNSUserPlans"

// GalloNSUserPlan 用户套餐
type GalloNSUserPlan struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID     int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	PlanID     int32  `gorm:"column:planId;comment:套餐ID" json:"planId"`                     // 套餐ID
	DayFrom    string `gorm:"column:dayFrom;comment:YYYYMMDD" json:"dayFrom"`               // YYYYMMDD
	DayTo      string `gorm:"column:dayTo;comment:YYYYMMDD" json:"dayTo"`                   // YYYYMMDD
	PeriodUnit string `gorm:"column:periodUnit;comment:monthly|yearly" json:"periodUnit"`   // monthly|yearly
	CreatedAt  int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	State      bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNSUserPlan's table name
func (*GalloNSUserPlan) TableName() string {
	return TableNameGalloNSUserPlan
}
