// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSDomain = "galloNSDomains"

// GalloNSDomain DNS域名
type GalloNSDomain struct {
	ID                 int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`         // ID
	ClusterID          int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`                       // 集群ID
	UserID             int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                             // 用户ID
	IsOn               bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                       // 是否启用
	Name               string `gorm:"column:name;comment:域名" json:"name"`                                   // 域名
	GroupIds           string `gorm:"column:groupIds;comment:分组ID" json:"groupIds"`                         // 分组ID
	Tsig               string `gorm:"column:tsig;comment:TSIG配置" json:"tsig"`                               // TSIG配置
	VerifyTXT          string `gorm:"column:verifyTXT;comment:验证用的TXT" json:"verifyTXT"`                    // 验证用的TXT
	VerifyExpiresAt    int64  `gorm:"column:verifyExpiresAt;comment:验证TXT过期时间" json:"verifyExpiresAt"`      // 验证TXT过期时间
	RecordsHealthCheck string `gorm:"column:recordsHealthCheck;comment:记录健康检查设置" json:"recordsHealthCheck"` // 记录健康检查设置
	CreatedAt          int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                       // 创建时间
	Version            int64  `gorm:"column:version;comment:版本号" json:"version"`                            // 版本号
	Status             string `gorm:"column:status;default:none;comment:状态：none|verified" json:"status"`    // 状态：none|verified
	State              bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                       // 状态
}

// TableName GalloNSDomain's table name
func (*GalloNSDomain) TableName() string {
	return TableNameGalloNSDomain
}
