// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeValue = "galloNodeValues"

// GalloNodeValue 节点监控数据
type GalloNodeValue struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ClusterID int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	NodeID    int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                     // 节点ID
	Role      string `gorm:"column:role;comment:节点角色" json:"role"`                         // 节点角色
	Item      string `gorm:"column:item;comment:监控项" json:"item"`                          // 监控项
	Value     string `gorm:"column:value;comment:数据" json:"value"`                         // 数据
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	Day       string `gorm:"column:day;comment:日期" json:"day"`                             // 日期
	Hour      string `gorm:"column:hour;comment:小时" json:"hour"`                           // 小时
	Minute    string `gorm:"column:minute;comment:分钟" json:"minute"`                       // 分钟
}

// TableName GalloNodeValue's table name
func (*GalloNodeValue) TableName() string {
	return TableNameGalloNodeValue
}
