// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerRegionCityMonthlyStat = "galloServerRegionCityMonthlyStats"

// GalloServerRegionCityMonthlyStat 服务用户省份分布统计（按天）
type GalloServerRegionCityMonthlyStat struct {
	ID       int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ServerID int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                 // 服务ID
	CityID   int32  `gorm:"column:cityId;comment:城市ID" json:"cityId"`                     // 城市ID
	Month    string `gorm:"column:month;comment:月份YYYYMM" json:"month"`                   // 月份YYYYMM
	Count    int64  `gorm:"column:count;comment:数量" json:"count"`                         // 数量
}

// TableName GalloServerRegionCityMonthlyStat's table name
func (*GalloServerRegionCityMonthlyStat) TableName() string {
	return TableNameGalloServerRegionCityMonthlyStat
}
