// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloIPLibrary = "galloIPLibraries"

// GalloIPLibrary IP库
type GalloIPLibrary struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID   int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	FileID    int32  `gorm:"column:fileId;comment:文件ID" json:"fileId"`                     // 文件ID
	Type      string `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	Name      string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	IsPublic  bool   `gorm:"column:isPublic;comment:是否公用" json:"isPublic"`                 // 是否公用
	State     bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
}

// TableName GalloIPLibrary's table name
func (*GalloIPLibrary) TableName() string {
	return TableNameGalloIPLibrary
}
