// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloOrderMethod = "galloOrderMethods"

// GalloOrderMethod 订单支付方式
type GalloOrderMethod struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name        string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	IsOn        bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Description string `gorm:"column:description;comment:描述" json:"description"`             // 描述
	ParentCode  string `gorm:"column:parentCode;comment:内置的父级代号" json:"parentCode"`          // 内置的父级代号
	Code        string `gorm:"column:code;comment:代号" json:"code"`                           // 代号
	URL         string `gorm:"column:url;comment:URL" json:"url"`                            // URL
	Secret      string `gorm:"column:secret;comment:密钥" json:"secret"`                       // 密钥
	Params      string `gorm:"column:params;comment:参数" json:"params"`                       // 参数
	ClientType  string `gorm:"column:clientType;comment:客户端类型" json:"clientType"`            // 客户端类型
	QrcodeTitle string `gorm:"column:qrcodeTitle;comment:二维码标题" json:"qrcodeTitle"`          // 二维码标题
	Order       int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	State       bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloOrderMethod's table name
func (*GalloOrderMethod) TableName() string {
	return TableNameGalloOrderMethod
}
