// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPWebsocket = "galloHTTPWebsockets"

// GalloHTTPWebsocket Websocket设置
type GalloHTTPWebsocket struct {
	ID                int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                      // ID
	AdminID           int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                                       // 管理员ID
	UserID            int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                                          // 用户ID
	CreatedAt         int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                                    // 创建时间
	State             bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                                    // 状态
	IsOn              bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                                    // 是否启用
	HandshakeTimeout  string `gorm:"column:handshakeTimeout;comment:握手超时时间" json:"handshakeTimeout"`                    // 握手超时时间
	AllowAllOrigins   bool   `gorm:"column:allowAllOrigins;default:1;comment:是否支持所有源" json:"allowAllOrigins"`           // 是否支持所有源
	AllowedOrigins    string `gorm:"column:allowedOrigins;comment:支持的源域名列表" json:"allowedOrigins"`                      // 支持的源域名列表
	RequestSameOrigin bool   `gorm:"column:requestSameOrigin;default:1;comment:是否请求一样的Origin" json:"requestSameOrigin"` // 是否请求一样的Origin
	RequestOrigin     string `gorm:"column:requestOrigin;comment:请求Origin" json:"requestOrigin"`                        // 请求Origin
	WebID             int64  `gorm:"column:webId;comment:Web" json:"webId"`                                             // Web
}

// TableName GalloHTTPWebsocket's table name
func (*GalloHTTPWebsocket) TableName() string {
	return TableNameGalloHTTPWebsocket
}
