// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPFastcgi = "galloHTTPFastcgis"

// GalloHTTPFastcgi Fastcgi设置
type GalloHTTPFastcgi struct {
	ID              int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`      // ID
	AdminID         int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                       // 管理员ID
	UserID          int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                          // 用户ID
	IsOn            bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                    // 是否启用
	Address         string `gorm:"column:address;comment:地址" json:"address"`                          // 地址
	Params          string `gorm:"column:params;comment:参数" json:"params"`                            // 参数
	ReadTimeout     string `gorm:"column:readTimeout;comment:读取超时" json:"readTimeout"`                // 读取超时
	ConnTimeout     string `gorm:"column:connTimeout;comment:连接超时" json:"connTimeout"`                // 连接超时
	PoolSize        int32  `gorm:"column:poolSize;comment:连接池尺寸" json:"poolSize"`                     // 连接池尺寸
	PathInfoPattern string `gorm:"column:pathInfoPattern;comment:PATH_INFO匹配" json:"pathInfoPattern"` // PATH_INFO匹配
	State           bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                    // 状态
}

// TableName GalloHTTPFastcgi's table name
func (*GalloHTTPFastcgi) TableName() string {
	return TableNameGalloHTTPFastcgi
}
