// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeGrant = "galloNodeGrants"

// GalloNodeGrant 节点授权
type GalloNodeGrant struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID     int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	Name        string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	Method      string `gorm:"column:method;comment:登录方式" json:"method"`                     // 登录方式
	Username    string `gorm:"column:username;comment:用户名" json:"username"`                  // 用户名
	Password    string `gorm:"column:password;comment:密码" json:"password"`                   // 密码
	Su          bool   `gorm:"column:su;comment:是否需要su" json:"su"`                           // 是否需要su
	PrivateKey  string `gorm:"column:privateKey;comment:私钥" json:"privateKey"`               // 私钥
	Passphrase  string `gorm:"column:passphrase;comment:私钥密码" json:"passphrase"`             // 私钥密码
	Description string `gorm:"column:description;comment:备注" json:"description"`             // 备注
	NodeID      int32  `gorm:"column:nodeId;comment:专有节点" json:"nodeId"`                     // 专有节点
	Role        string `gorm:"column:role;default:node;comment:角色" json:"role"`              // 角色
	State       bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	CreatedAt   int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
}

// TableName GalloNodeGrant's table name
func (*GalloNodeGrant) TableName() string {
	return TableNameGalloNodeGrant
}
