// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloSSLCert = "galloSSLCerts"

// GalloSSLCert SSL证书
type GalloSSLCert struct {
	ID                 int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`         // ID
	AdminID            int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                          // 管理员ID
	UserID             int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                             // 用户ID
	State              bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                       // 状态
	CreatedAt          int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                       // 创建时间
	UpdatedAt          int64  `gorm:"column:updatedAt;comment:修改时间" json:"updatedAt"`                       // 修改时间
	IsOn               bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                       // 是否启用
	Name               string `gorm:"column:name;comment:证书名" json:"name"`                                  // 证书名
	Description        string `gorm:"column:description;comment:描述" json:"description"`                     // 描述
	CertData           []byte `gorm:"column:certData;comment:证书内容" json:"certData"`                         // 证书内容
	KeyData            []byte `gorm:"column:keyData;comment:密钥内容" json:"keyData"`                           // 密钥内容
	ServerName         string `gorm:"column:serverName;comment:证书使用的主机名" json:"serverName"`                 // 证书使用的主机名
	IsCA               bool   `gorm:"column:isCA;comment:是否为CA证书" json:"isCA"`                              // 是否为CA证书
	GroupIds           string `gorm:"column:groupIds;comment:证书分组" json:"groupIds"`                         // 证书分组
	TimeBeginAt        int64  `gorm:"column:timeBeginAt;comment:开始时间" json:"timeBeginAt"`                   // 开始时间
	TimeEndAt          int64  `gorm:"column:timeEndAt;comment:结束时间" json:"timeEndAt"`                       // 结束时间
	DNSNames           string `gorm:"column:dnsNames;comment:DNS名称列表" json:"dnsNames"`                      // DNS名称列表
	CommonNames        string `gorm:"column:commonNames;comment:发行单位列表" json:"commonNames"`                 // 发行单位列表
	IsACME             bool   `gorm:"column:isACME;comment:是否为ACME自动生成的" json:"isACME"`                     // 是否为ACME自动生成的
	AcmeTaskID         int64  `gorm:"column:acmeTaskId;comment:ACME任务ID" json:"acmeTaskId"`                 // ACME任务ID
	NotifiedAt         int64  `gorm:"column:notifiedAt;comment:最后通知时间" json:"notifiedAt"`                   // 最后通知时间
	Ocsp               []byte `gorm:"column:ocsp;comment:OCSP缓存" json:"ocsp"`                               // OCSP缓存
	OcspIsUpdated      bool   `gorm:"column:ocspIsUpdated;comment:OCSP是否已更新" json:"ocspIsUpdated"`          // OCSP是否已更新
	OcspUpdatedAt      int64  `gorm:"column:ocspUpdatedAt;comment:OCSP更新时间" json:"ocspUpdatedAt"`           // OCSP更新时间
	OcspError          string `gorm:"column:ocspError;comment:OCSP更新错误" json:"ocspError"`                   // OCSP更新错误
	OcspUpdatedVersion int64  `gorm:"column:ocspUpdatedVersion;comment:OCSP更新版本" json:"ocspUpdatedVersion"` // OCSP更新版本
	OcspExpiresAt      int64  `gorm:"column:ocspExpiresAt;comment:OCSP过期时间(UTC)" json:"ocspExpiresAt"`      // OCSP过期时间(UTC)
	OcspTries          int32  `gorm:"column:ocspTries;comment:OCSP尝试次数" json:"ocspTries"`                   // OCSP尝试次数
}

// TableName GalloSSLCert's table name
func (*GalloSSLCert) TableName() string {
	return TableNameGalloSSLCert
}
