// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerGroup = "galloServerGroups"

// GalloServerGroup 服务分组
type GalloServerGroup struct {
	ID               int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`   // ID
	AdminID          int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                    // 管理员ID
	UserID           int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                       // 用户ID
	IsOn             bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                 // 是否启用
	Name             string `gorm:"column:name;comment:名称" json:"name"`                             // 名称
	Order            int32  `gorm:"column:order;comment:排序" json:"order"`                           // 排序
	CreatedAt        int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                 // 创建时间
	State            bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                 // 状态
	HTTPReverseProxy string `gorm:"column:httpReverseProxy;comment:反向代理设置" json:"httpReverseProxy"` // 反向代理设置
	TcpReverseProxy  string `gorm:"column:tcpReverseProxy;comment:TCP反向代理" json:"tcpReverseProxy"`  // TCP反向代理
	UdpReverseProxy  string `gorm:"column:udpReverseProxy;comment:UDP反向代理" json:"udpReverseProxy"`  // UDP反向代理
	WebID            int32  `gorm:"column:webId;comment:Web配置ID" json:"webId"`                      // Web配置ID
}

// TableName GalloServerGroup's table name
func (*GalloServerGroup) TableName() string {
	return TableNameGalloServerGroup
}
