// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserEmailVerification = "galloUserEmailVerifications"

// GalloUserEmailVerification 邮箱激活邮件队列
type GalloUserEmailVerification struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Email      string `gorm:"column:email;comment:邮箱" json:"email"`                         // 邮箱
	UserID     int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Code       string `gorm:"column:code;comment:激活码" json:"code"`                          // 激活码
	CreatedAt  int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	IsSent     bool   `gorm:"column:isSent;comment:是否已发送" json:"isSent"`                    // 是否已发送
	IsVerified bool   `gorm:"column:isVerified;comment:是否已激活" json:"isVerified"`            // 是否已激活
	Day        string `gorm:"column:day;comment:YYYYMMDD" json:"day"`                       // YYYYMMDD
}

// TableName GalloUserEmailVerification's table name
func (*GalloUserEmailVerification) TableName() string {
	return TableNameGalloUserEmailVerification
}
