// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

import (
	"time"
)

const TableNameGalloUserPlan = "galloUserPlans"

// GalloUserPlan 用户的套餐
type GalloUserPlan struct {
	ID     int64     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID int32     `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	PlanID int32     `gorm:"column:planId;comment:套餐ID" json:"planId"`                     // 套餐ID
	IsOn   bool      `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Name   string    `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	DayTo  time.Time `gorm:"column:dayTo;comment:结束日期" json:"dayTo"`                       // 结束日期
	State  bool      `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloUserPlan's table name
func (*GalloUserPlan) TableName() string {
	return TableNameGalloUserPlan
}
