// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloLatestItem = "galloLatestItems"

// GalloLatestItem 最近的条目统计
type GalloLatestItem struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ItemType  string `gorm:"column:itemType;comment:Item类型" json:"itemType"`               // Item类型
	ItemID    int64  `gorm:"column:itemId;comment:itemID" json:"itemId"`                   // itemID
	Count     int64  `gorm:"column:count;comment:数量" json:"count"`                         // 数量
	UpdatedAt int64  `gorm:"column:updatedAt;comment:更新时间" json:"updatedAt"`               // 更新时间
}

// TableName GalloLatestItem's table name
func (*GalloLatestItem) TableName() string {
	return TableNameGalloLatestItem
}
