// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloAPIToken = "galloAPITokens"

// GalloAPIToken API令牌管理
type GalloAPIToken struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	NodeID string `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                     // 节点ID
	Secret string `gorm:"column:secret;comment:节点密钥" json:"secret"`                     // 节点密钥
	Role   string `gorm:"column:role;comment:节点角色" json:"role"`                         // 节点角色
	State  bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloAPIToken's table name
func (*GalloAPIToken) TableName() string {
	return TableNameGalloAPIToken
}
