// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloAPIAccessToken = "galloAPIAccessTokens"

// GalloAPIAccessToken API访问令牌
type GalloAPIAccessToken struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID    int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	AdminID   int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	Token     string `gorm:"column:token;comment:令牌" json:"token"`                         // 令牌
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	ExpiredAt int64  `gorm:"column:expiredAt;comment:过期时间" json:"expiredAt"`               // 过期时间
}

// TableName GalloAPIAccessToken's table name
func (*GalloAPIAccessToken) TableName() string {
	return TableNameGalloAPIAccessToken
}
