// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerHTTPFirewallHourlyStat = "galloServerHTTPFirewallHourlyStats"

// GalloServerHTTPFirewallHourlyStat WAF统计
type GalloServerHTTPFirewallHourlyStat struct {
	ID                      int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`                  // ID
	ServerID                int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                                  // 服务ID
	Day                     string `gorm:"column:day;comment:YYYYMMDD" json:"day"`                                        // YYYYMMDD
	Hour                    string `gorm:"column:hour;comment:YYYYMMDDHH" json:"hour"`                                    // YYYYMMDDHH
	HTTPFirewallRuleGroupID int32  `gorm:"column:httpFirewallRuleGroupId;comment:WAF分组ID" json:"httpFirewallRuleGroupId"` // WAF分组ID
	Action                  string `gorm:"column:action;comment:采取的动作" json:"action"`                                     // 采取的动作
	Count                   int64  `gorm:"column:count;comment:数量" json:"count"`                                          // 数量
}

// TableName GalloServerHTTPFirewallHourlyStat's table name
func (*GalloServerHTTPFirewallHourlyStat) TableName() string {
	return TableNameGalloServerHTTPFirewallHourlyStat
}
