// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserAccountLog = "galloUserAccountLogs"

// GalloUserAccountLog 用户账户日志
type GalloUserAccountLog struct {
	ID          int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`            // ID
	UserID      int64   `gorm:"column:userId;comment:用户ID" json:"userId"`                                // 用户ID
	AccountID   int64   `gorm:"column:accountId;comment:账户ID" json:"accountId"`                          // 账户ID
	Delta       float64 `gorm:"column:delta;default:0.00;comment:操作余额的数量（可为负）" json:"delta"`             // 操作余额的数量（可为负）
	DeltaFrozen float64 `gorm:"column:deltaFrozen;default:0.00;comment:操作冻结的数量（可为负）" json:"deltaFrozen"` // 操作冻结的数量（可为负）
	Total       float64 `gorm:"column:total;default:0.00;comment:操作后余额" json:"total"`                    // 操作后余额
	TotalFrozen float64 `gorm:"column:totalFrozen;default:0.00;comment:操作后冻结余额" json:"totalFrozen"`      // 操作后冻结余额
	EventType   string  `gorm:"column:eventType;comment:类型" json:"eventType"`                            // 类型
	Description string  `gorm:"column:description;comment:描述文字" json:"description"`                      // 描述文字
	Day         string  `gorm:"column:day;comment:YYYYMMDD" json:"day"`                                  // YYYYMMDD
	CreatedAt   int64   `gorm:"column:createdAt;comment:时间" json:"createdAt"`                            // 时间
	Params      string  `gorm:"column:params;comment:参数" json:"params"`                                  // 参数
}

// TableName GalloUserAccountLog's table name
func (*GalloUserAccountLog) TableName() string {
	return TableNameGalloUserAccountLog
}
