// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloMessageReceiver = "galloMessageReceivers"

// GalloMessageReceiver 消息通知接收人
type GalloMessageReceiver struct {
	ID               int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`    // ID
	Role             string `gorm:"column:role;default:node;comment:节点角色" json:"role"`               // 节点角色
	ClusterID        int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`                  // 集群ID
	NodeID           int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                        // 节点ID
	ServerID         int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                    // 服务ID
	Type             string `gorm:"column:type;comment:类型" json:"type"`                              // 类型
	Params           string `gorm:"column:params;comment:参数" json:"params"`                          // 参数
	RecipientID      int32  `gorm:"column:recipientId;comment:接收人ID" json:"recipientId"`             // 接收人ID
	RecipientGroupID int32  `gorm:"column:recipientGroupId;comment:接收人分组ID" json:"recipientGroupId"` // 接收人分组ID
	State            bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                  // 状态
}

// TableName GalloMessageReceiver's table name
func (*GalloMessageReceiver) TableName() string {
	return TableNameGalloMessageReceiver
}
