// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPAccessLog = "galloHTTPAccessLogs"

// GalloHTTPAccessLog 访问日志
type GalloHTTPAccessLog struct {
	ID                  int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`          // ID
	ServerID            int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                          // 服务ID
	NodeID              int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                              // 节点ID
	Status              int32  `gorm:"column:status;comment:状态码" json:"status"`                               // 状态码
	CreatedAt           int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                        // 创建时间
	Content             string `gorm:"column:content;comment:日志内容" json:"content"`                            // 日志内容
	RequestID           string `gorm:"column:requestId;comment:请求ID" json:"requestId"`                        // 请求ID
	FirewallPolicyID    int32  `gorm:"column:firewallPolicyId;comment:WAF策略ID" json:"firewallPolicyId"`       // WAF策略ID
	FirewallRuleGroupID int32  `gorm:"column:firewallRuleGroupId;comment:WAF分组ID" json:"firewallRuleGroupId"` // WAF分组ID
	FirewallRuleSetID   int32  `gorm:"column:firewallRuleSetId;comment:WAF集ID" json:"firewallRuleSetId"`      // WAF集ID
	FirewallRuleID      int32  `gorm:"column:firewallRuleId;comment:WAF规则ID" json:"firewallRuleId"`           // WAF规则ID
	RemoteAddr          string `gorm:"column:remoteAddr;comment:IP地址" json:"remoteAddr"`                      // IP地址
	Domain              string `gorm:"column:domain;comment:域名" json:"domain"`                                // 域名
	RequestBody         []byte `gorm:"column:requestBody;comment:请求内容" json:"requestBody"`                    // 请求内容
	ResponseBody        []byte `gorm:"column:responseBody;comment:响应内容" json:"responseBody"`                  // 响应内容
}

// TableName GalloHTTPAccessLog's table name
func (*GalloHTTPAccessLog) TableName() string {
	return TableNameGalloHTTPAccessLog
}
