// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeLog = "galloNodeLogs"

// GalloNodeLog 节点日志
type GalloNodeLog struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Role        string `gorm:"column:role;comment:节点角色" json:"role"`                         // 节点角色
	Type        string `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	CreatedAt   int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	Tag         string `gorm:"column:tag;comment:标签" json:"tag"`                             // 标签
	Description string `gorm:"column:description;comment:描述" json:"description"`             // 描述
	Level       string `gorm:"column:level;comment:级别" json:"level"`                         // 级别
	NodeID      int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                     // 节点ID
	Day         string `gorm:"column:day;comment:日期" json:"day"`                             // 日期
	ServerID    int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                 // 服务ID
	OriginID    int32  `gorm:"column:originId;comment:源站ID" json:"originId"`                 // 源站ID
	Hash        string `gorm:"column:hash;comment:信息内容Hash" json:"hash"`                     // 信息内容Hash
	Count       int32  `gorm:"column:count;comment:重复次数" json:"count"`                       // 重复次数
	IsFixed     bool   `gorm:"column:isFixed;comment:是否已处理" json:"isFixed"`                  // 是否已处理
	IsRead      bool   `gorm:"column:isRead;default:1;comment:是否已读" json:"isRead"`           // 是否已读
	Params      string `gorm:"column:params;comment:参数" json:"params"`                       // 参数
}

// TableName GalloNodeLog's table name
func (*GalloNodeLog) TableName() string {
	return TableNameGalloNodeLog
}
