// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloIPList = "galloIPLists"

// GalloIPList IP名单
type GalloIPList struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	IsOn        bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Type        string `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	AdminID     int32  `gorm:"column:adminId;comment:用户ID" json:"adminId"`                   // 用户ID
	UserID      int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	ServerID    int64  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                 // 服务ID
	Name        string `gorm:"column:name;comment:列表名" json:"name"`                          // 列表名
	Code        string `gorm:"column:code;comment:代号" json:"code"`                           // 代号
	State       bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	CreatedAt   int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	Timeout     string `gorm:"column:timeout;comment:默认超时时间" json:"timeout"`                 // 默认超时时间
	Actions     string `gorm:"column:actions;comment:IP触发的动作" json:"actions"`                // IP触发的动作
	Description string `gorm:"column:description;comment:描述" json:"description"`             // 描述
	IsPublic    bool   `gorm:"column:isPublic;comment:是否公用" json:"isPublic"`                 // 是否公用
	IsGlobal    bool   `gorm:"column:isGlobal;comment:是否全局" json:"isGlobal"`                 // 是否全局
}

// TableName GalloIPList's table name
func (*GalloIPList) TableName() string {
	return TableNameGalloIPList
}
