// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerRegionCountryMonthlyStat = "galloServerRegionCountryMonthlyStats"

// GalloServerRegionCountryMonthlyStat 服务用户区域分布统计（按天）
type GalloServerRegionCountryMonthlyStat struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ServerID  int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                 // 服务ID
	CountryID int32  `gorm:"column:countryId;comment:国家/区域ID" json:"countryId"`            // 国家/区域ID
	Month     string `gorm:"column:month;comment:月份YYYYMM" json:"month"`                   // 月份YYYYMM
	Count     int64  `gorm:"column:count;comment:数量" json:"count"`                         // 数量
}

// TableName GalloServerRegionCountryMonthlyStat's table name
func (*GalloServerRegionCountryMonthlyStat) TableName() string {
	return TableNameGalloServerRegionCountryMonthlyStat
}
