// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloTCPFirewallPolicy = "galloTCPFirewallPolicies"

// GalloTCPFirewallPolicy TCP防火墙
type GalloTCPFirewallPolicy struct {
	ID         int32 `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID    int32 `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID     int32 `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	TemplateID int32 `gorm:"column:templateId;comment:模版ID" json:"templateId"`             // 模版ID
}

// TableName GalloTCPFirewallPolicy's table name
func (*GalloTCPFirewallPolicy) TableName() string {
	return TableNameGalloTCPFirewallPolicy
}
