// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloACMETask = "galloACMETasks"

// GalloACMETask ACME任务
type GalloACMETask struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AdminID       int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID        int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	IsOn          bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	AcmeUserID    int32  `gorm:"column:acmeUserId;comment:ACME用户ID" json:"acmeUserId"`         // ACME用户ID
	DNSDomain     string `gorm:"column:dnsDomain;comment:DNS主域名" json:"dnsDomain"`             // DNS主域名
	DNSProviderID int64  `gorm:"column:dnsProviderId;comment:DNS服务商" json:"dnsProviderId"`     // DNS服务商
	Domains       string `gorm:"column:domains;comment:证书域名" json:"domains"`                   // 证书域名
	CreatedAt     int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	State         bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	CertID        int64  `gorm:"column:certId;comment:生成的证书ID" json:"certId"`                  // 生成的证书ID
	AutoRenew     bool   `gorm:"column:autoRenew;comment:是否自动更新" json:"autoRenew"`             // 是否自动更新
	AuthType      string `gorm:"column:authType;comment:认证类型" json:"authType"`                 // 认证类型
	AuthURL       string `gorm:"column:authURL;comment:认证URL" json:"authURL"`                  // 认证URL
}

// TableName GalloACMETask's table name
func (*GalloACMETask) TableName() string {
	return TableNameGalloACMETask
}
