// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloMessageMediaInstance = "galloMessageMediaInstances"

// GalloMessageMediaInstance 消息媒介接收人
type GalloMessageMediaInstance struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name        string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	IsOn        bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	MediaType   string `gorm:"column:mediaType;comment:媒介类型" json:"mediaType"`               // 媒介类型
	Params      string `gorm:"column:params;comment:媒介参数" json:"params"`                     // 媒介参数
	Description string `gorm:"column:description;comment:备注" json:"description"`             // 备注
	Rate        string `gorm:"column:rate;comment:发送频率" json:"rate"`                         // 发送频率
	State       bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	HashLife    int32  `gorm:"column:hashLife;comment:HASH有效期（秒）" json:"hashLife"`           // HASH有效期（秒）
}

// TableName GalloMessageMediaInstance's table name
func (*GalloMessageMediaInstance) TableName() string {
	return TableNameGalloMessageMediaInstance
}
