// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

import (
	"time"
)

const TableNameGalloAuthorityKey = "galloAuthorityKeys"

// GalloAuthorityKey 企业版认证信息
type GalloAuthorityKey struct {
	ID           int32     `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Value        string    `gorm:"column:value;comment:Key值" json:"value"`                       // Key值
	DayFrom      time.Time `gorm:"column:dayFrom;comment:开始日期" json:"dayFrom"`                   // 开始日期
	DayTo        time.Time `gorm:"column:dayTo;comment:结束日期" json:"dayTo"`                       // 结束日期
	Hostname     string    `gorm:"column:hostname;comment:Hostname" json:"hostname"`             // Hostname
	MacAddresses string    `gorm:"column:macAddresses;comment:MAC地址" json:"macAddresses"`        // MAC地址
	UpdatedAt    int64     `gorm:"column:updatedAt;comment:创建/修改时间" json:"updatedAt"`            // 创建/修改时间
	Company      string    `gorm:"column:company;comment:公司组织" json:"company"`                   // 公司组织
	RequestCode  string    `gorm:"column:requestCode;comment:申请码" json:"requestCode"`            // 申请码
}

// TableName GalloAuthorityKey's table name
func (*GalloAuthorityKey) TableName() string {
	return TableNameGalloAuthorityKey
}
