// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloScript = "galloScripts"

// GalloScript 脚本库
type GalloScript struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID    int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	IsOn      bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Name      string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	Filename  string `gorm:"column:filename;comment:文件名" json:"filename"`                  // 文件名
	Code      string `gorm:"column:code;comment:代码" json:"code"`                           // 代码
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	UpdatedAt int64  `gorm:"column:updatedAt;comment:修改时间" json:"updatedAt"`               // 修改时间
	State     bool   `gorm:"column:state;default:1;comment:是否启用" json:"state"`             // 是否启用
}

// TableName GalloScript's table name
func (*GalloScript) TableName() string {
	return TableNameGalloScript
}
