// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserScript = "galloUserScripts"

// GalloUserScript 用户脚本审核
type GalloUserScript struct {
	ID             int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID         int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	AdminID        int64  `gorm:"column:adminId;comment:操作管理员" json:"adminId"`                  // 操作管理员
	Code           string `gorm:"column:code;comment:代码" json:"code"`                           // 代码
	CodeMD5        string `gorm:"column:codeMD5;comment:代码MD5" json:"codeMD5"`                  // 代码MD5
	CreatedAt      int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	IsRejected     bool   `gorm:"column:isRejected;comment:是否已驳回" json:"isRejected"`            // 是否已驳回
	RejectedAt     int64  `gorm:"column:rejectedAt;comment:驳回时间" json:"rejectedAt"`             // 驳回时间
	RejectedReason string `gorm:"column:rejectedReason;comment:驳回原因" json:"rejectedReason"`     // 驳回原因
	IsPassed       bool   `gorm:"column:isPassed;comment:是否通过审核" json:"isPassed"`               // 是否通过审核
	PassedAt       int64  `gorm:"column:passedAt;comment:通过时间" json:"passedAt"`                 // 通过时间
	State          bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	WebIds         string `gorm:"column:webIds;comment:WebId列表" json:"webIds"`                  // WebId列表
}

// TableName GalloUserScript's table name
func (*GalloUserScript) TableName() string {
	return TableNameGalloUserScript
}
