// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloProvider = "galloProviders"

// GalloProvider 供应商
type GalloProvider struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Username  string `gorm:"column:username;comment:用户名" json:"username"`                  // 用户名
	Password  string `gorm:"column:password;comment:密码" json:"password"`                   // 密码
	Fullname  string `gorm:"column:fullname;comment:真实姓名" json:"fullname"`                 // 真实姓名
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	UpdatedAt int64  `gorm:"column:updatedAt;comment:修改时间" json:"updatedAt"`               // 修改时间
	State     bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloProvider's table name
func (*GalloProvider) TableName() string {
	return TableNameGalloProvider
}
