// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSKey = "galloNSKeys"

// GalloNSKey 密钥管理
type GalloNSKey struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	IsOn       bool   `gorm:"column:isOn;default:1;comment:状态" json:"isOn"`                 // 状态
	Name       string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	DomainID   int64  `gorm:"column:domainId;comment:域名ID" json:"domainId"`                 // 域名ID
	ZoneID     int64  `gorm:"column:zoneId;comment:子域ID" json:"zoneId"`                     // 子域ID
	Algo       string `gorm:"column:algo;comment:算法" json:"algo"`                           // 算法
	Secret     string `gorm:"column:secret;comment:密码" json:"secret"`                       // 密码
	SecretType string `gorm:"column:secretType;comment:密码类型" json:"secretType"`             // 密码类型
	Version    int64  `gorm:"column:version;comment:版本号" json:"version"`                    // 版本号
	State      bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNSKey's table name
func (*GalloNSKey) TableName() string {
	return TableNameGalloNSKey
}
