// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloMessageTask = "galloMessageTasks"

// GalloMessageTask 消息发送相关任务
type GalloMessageTask struct {
	ID          int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	RecipientID int32  `gorm:"column:recipientId;comment:接收人ID" json:"recipientId"`          // 接收人ID
	Hash        string `gorm:"column:hash;comment:SUM标识" json:"hash"`                        // SUM标识
	InstanceID  int32  `gorm:"column:instanceId;comment:媒介实例ID" json:"instanceId"`           // 媒介实例ID
	User        string `gorm:"column:user;comment:接收用户标识" json:"user"`                       // 接收用户标识
	Subject     string `gorm:"column:subject;comment:标题" json:"subject"`                     // 标题
	Body        string `gorm:"column:body;comment:内容" json:"body"`                           // 内容
	CreatedAt   int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	Status      bool   `gorm:"column:status;comment:发送状态" json:"status"`                     // 发送状态
	SentAt      int64  `gorm:"column:sentAt;comment:最后一次发送时间" json:"sentAt"`                 // 最后一次发送时间
	State       bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	Result      string `gorm:"column:result;comment:结果" json:"result"`                       // 结果
	Day         string `gorm:"column:day;comment:YYYYMMDD" json:"day"`                       // YYYYMMDD
	IsPrimary   bool   `gorm:"column:isPrimary;comment:是否优先" json:"isPrimary"`               // 是否优先
}

// TableName GalloMessageTask's table name
func (*GalloMessageTask) TableName() string {
	return TableNameGalloMessageTask
}
