// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloADPackagePeriod = "galloADPackagePeriods"

// GalloADPackagePeriod 高防产品有效期
type GalloADPackagePeriod struct {
	ID     int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	IsOn   bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Count  int32  `gorm:"column:count;comment:数量" json:"count"`                         // 数量
	Unit   string `gorm:"column:unit;comment:单位：month, year" json:"unit"`               // 单位：month, year
	Months int32  `gorm:"column:months;comment:月数" json:"months"`                       // 月数
	State  bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloADPackagePeriod's table name
func (*GalloADPackagePeriod) TableName() string {
	return TableNameGalloADPackagePeriod
}
