// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloMetricItem = "galloMetricItems"

// GalloMetricItem 指标定义
type GalloMetricItem struct {
	ID            int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	IsOn          bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Code          string `gorm:"column:code;comment:代号（用来区分是否内置）" json:"code"`                 // 代号（用来区分是否内置）
	Category      string `gorm:"column:category;comment:类型，比如http, tcp等" json:"category"`      // 类型，比如http, tcp等
	AdminID       int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID        int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Name          string `gorm:"column:name;comment:指标名称" json:"name"`                         // 指标名称
	Keys          string `gorm:"column:keys;comment:统计的Key" json:"keys"`                       // 统计的Key
	Period        int32  `gorm:"column:period;comment:周期" json:"period"`                       // 周期
	PeriodUnit    string `gorm:"column:periodUnit;comment:周期单位" json:"periodUnit"`             // 周期单位
	ExpiresPeriod int32  `gorm:"column:expiresPeriod;comment:过期周期" json:"expiresPeriod"`       // 过期周期
	Value         string `gorm:"column:value;comment:值运算" json:"value"`                        // 值运算
	State         bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	Version       int32  `gorm:"column:version;comment:版本号" json:"version"`                    // 版本号
	IsPublic      bool   `gorm:"column:isPublic;comment:是否为公用" json:"isPublic"`                // 是否为公用
	LastTime      string `gorm:"column:lastTime;comment:最新时间" json:"lastTime"`                 // 最新时间
}

// TableName GalloMetricItem's table name
func (*GalloMetricItem) TableName() string {
	return TableNameGalloMetricItem
}
