// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeIPAddressThreshold = "galloNodeIPAddressThresholds"

// GalloNodeIPAddressThreshold IP地址阈值
type GalloNodeIPAddressThreshold struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	AddressID  int64  `gorm:"column:addressId;comment:IP地址ID" json:"addressId"`             // IP地址ID
	Items      string `gorm:"column:items;comment:阈值条目" json:"items"`                       // 阈值条目
	Actions    string `gorm:"column:actions;comment:动作" json:"actions"`                     // 动作
	NotifiedAt int64  `gorm:"column:notifiedAt;comment:上次通知时间" json:"notifiedAt"`           // 上次通知时间
	IsMatched  bool   `gorm:"column:isMatched;comment:上次是否匹配" json:"isMatched"`             // 上次是否匹配
	State      bool   `gorm:"column:state;comment:状态" json:"state"`                         // 状态
	Order      int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
}

// TableName GalloNodeIPAddressThreshold's table name
func (*GalloNodeIPAddressThreshold) TableName() string {
	return TableNameGalloNodeIPAddressThreshold
}
