// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSDomainGroup = "galloNSDomainGroups"

// GalloNSDomainGroup 域名分组
type GalloNSDomainGroup struct {
	ID     int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Name   string `gorm:"column:name;comment:分组名称" json:"name"`                         // 分组名称
	IsOn   bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Order  int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	State  bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNSDomainGroup's table name
func (*GalloNSDomainGroup) TableName() string {
	return TableNameGalloNSDomainGroup
}
