// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSRoute = "galloNSRoutes"

// GalloNSRoute DNS线路
type GalloNSRoute struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	IsOn       bool   `gorm:"column:isOn;comment:是否启用" json:"isOn"`                         // 是否启用
	ClusterID  int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	CategoryID int32  `gorm:"column:categoryId;comment:分类ID" json:"categoryId"`             // 分类ID
	DomainID   int64  `gorm:"column:domainId;comment:域名ID" json:"domainId"`                 // 域名ID
	AdminID    int64  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID     int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	IsPublic   bool   `gorm:"column:isPublic;comment:是否公用（管理员创建的线路）" json:"isPublic"`       // 是否公用（管理员创建的线路）
	Name       string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	Ranges     string `gorm:"column:ranges;comment:范围" json:"ranges"`                       // 范围
	Order      int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	Version    int64  `gorm:"column:version;comment:版本号" json:"version"`                    // 版本号
	Priority   int32  `gorm:"column:priority;comment:优先级，越高越优先" json:"priority"`            // 优先级，越高越优先
	Code       string `gorm:"column:code;comment:代号" json:"code"`                           // 代号
	State      bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNSRoute's table name
func (*GalloNSRoute) TableName() string {
	return TableNameGalloNSRoute
}
