// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloClientBrowser = "galloClientBrowsers"

// GalloClientBrowser 终端浏览器信息
type GalloClientBrowser struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`              // ID
	Name       string `gorm:"column:name;comment:浏览器名称" json:"name"`                                     // 浏览器名称
	Codes      string `gorm:"column:codes;comment:代号" json:"codes"`                                      // 代号
	CreatedDay string `gorm:"column:createdDay;default:00000000;comment:创建日期YYYYMMDD" json:"createdDay"` // 创建日期YYYYMMDD
	State      bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                            // 状态
}

// TableName GalloClientBrowser's table name
func (*GalloClientBrowser) TableName() string {
	return TableNameGalloClientBrowser
}
