// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeTask = "galloNodeTasks"

// GalloNodeTask 节点同步任务
type GalloNodeTask struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Role       string `gorm:"column:role;default:node;comment:节点角色" json:"role"`            // 节点角色
	NodeID     int32  `gorm:"column:nodeId;comment:节点ID" json:"nodeId"`                     // 节点ID
	ClusterID  int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	ServerID   int64  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                 // 服务ID
	UserID     int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Type       string `gorm:"column:type;comment:任务类型" json:"type"`                         // 任务类型
	UniqueID   string `gorm:"column:uniqueId;comment:唯一ID：nodeId@type" json:"uniqueId"`     // 唯一ID：nodeId@type
	UpdatedAt  int64  `gorm:"column:updatedAt;comment:修改时间" json:"updatedAt"`               // 修改时间
	IsDone     bool   `gorm:"column:isDone;comment:是否已完成" json:"isDone"`                    // 是否已完成
	IsOk       bool   `gorm:"column:isOk;comment:是否已完成" json:"isOk"`                        // 是否已完成
	Error      string `gorm:"column:error;comment:错误信息" json:"error"`                       // 错误信息
	IsNotified bool   `gorm:"column:isNotified;comment:是否已通知更新" json:"isNotified"`          // 是否已通知更新
	Version    int64  `gorm:"column:version;comment:版本" json:"version"`                     // 版本
}

// TableName GalloNodeTask's table name
func (*GalloNodeTask) TableName() string {
	return TableNameGalloNodeTask
}
