// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloReportNodeGroup = "galloReportNodeGroups"

// GalloReportNodeGroup 监控终端区域
type GalloReportNodeGroup struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name  string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	State bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	IsOn  bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
}

// TableName GalloReportNodeGroup's table name
func (*GalloReportNodeGroup) TableName() string {
	return TableNameGalloReportNodeGroup
}
