// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloSSLPolicy = "galloSSLPolicies"

// GalloSSLPolicy SSL配置策略
type GalloSSLPolicy struct {
	ID               int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`         // ID
	AdminID          int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                          // 管理员ID
	UserID           int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                             // 用户ID
	IsOn             bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`                       // 是否启用
	Certs            string `gorm:"column:certs;comment:证书列表" json:"certs"`                               // 证书列表
	ClientCACerts    string `gorm:"column:clientCACerts;comment:客户端证书" json:"clientCACerts"`              // 客户端证书
	ClientAuthType   int32  `gorm:"column:clientAuthType;comment:客户端认证类型" json:"clientAuthType"`          // 客户端认证类型
	MinVersion       string `gorm:"column:minVersion;comment:支持的SSL最小版本" json:"minVersion"`               // 支持的SSL最小版本
	CipherSuitesIsOn bool   `gorm:"column:cipherSuitesIsOn;comment:是否自定义加密算法套件" json:"cipherSuitesIsOn"`  // 是否自定义加密算法套件
	CipherSuites     string `gorm:"column:cipherSuites;comment:加密算法套件" json:"cipherSuites"`               // 加密算法套件
	Hsts             string `gorm:"column:hsts;comment:HSTS设置" json:"hsts"`                               // HSTS设置
	Http2Enabled     bool   `gorm:"column:http2Enabled;default:1;comment:是否启用HTTP/2" json:"http2Enabled"` // 是否启用HTTP/2
	Http3Enabled     bool   `gorm:"column:http3Enabled;comment:是否启用HTTP/3" json:"http3Enabled"`           // 是否启用HTTP/3
	OcspIsOn         bool   `gorm:"column:ocspIsOn;comment:是否启用OCSP" json:"ocspIsOn"`                     // 是否启用OCSP
	State            bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                       // 状态
	CreatedAt        int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                       // 创建时间
}

// TableName GalloSSLPolicy's table name
func (*GalloSSLPolicy) TableName() string {
	return TableNameGalloSSLPolicy
}
