// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserTicketCategory = "galloUserTicketCategories"

// GalloUserTicketCategory 工单分类
type GalloUserTicketCategory struct {
	ID    int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name  string `gorm:"column:name;comment:分类名" json:"name"`                          // 分类名
	IsOn  bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Order int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	State bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloUserTicketCategory's table name
func (*GalloUserTicketCategory) TableName() string {
	return TableNameGalloUserTicketCategory
}
