// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloACMEProviderAccount = "galloACMEProviderAccounts"

// GalloACMEProviderAccount ACME提供商
type GalloACMEProviderAccount struct {
	ID           int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UserID       int64  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	IsOn         bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Name         string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	ProviderCode string `gorm:"column:providerCode;comment:代号" json:"providerCode"`           // 代号
	EabKid       string `gorm:"column:eabKid;comment:KID" json:"eabKid"`                      // KID
	EabKey       string `gorm:"column:eabKey;comment:Key" json:"eabKey"`                      // Key
	Error        string `gorm:"column:error;comment:最后一条错误信息" json:"error"`                   // 最后一条错误信息
	State        bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloACMEProviderAccount's table name
func (*GalloACMEProviderAccount) TableName() string {
	return TableNameGalloACMEProviderAccount
}
