// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerDailyStat = "galloServerDailyStats"

// GalloServerDailyStat 计费流量统计
type GalloServerDailyStat struct {
	ID                  int64   `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`         // ID
	UserID              int32   `gorm:"column:userId;comment:用户ID" json:"userId"`                             // 用户ID
	ServerID            int32   `gorm:"column:serverId;comment:服务ID" json:"serverId"`                         // 服务ID
	RegionID            int32   `gorm:"column:regionId;comment:区域ID" json:"regionId"`                         // 区域ID
	Bytes               int64   `gorm:"column:bytes;comment:流量" json:"bytes"`                                 // 流量
	CachedBytes         int64   `gorm:"column:cachedBytes;comment:缓存的流量" json:"cachedBytes"`                  // 缓存的流量
	CountRequests       int64   `gorm:"column:countRequests;comment:请求数" json:"countRequests"`                // 请求数
	CountCachedRequests int64   `gorm:"column:countCachedRequests;comment:缓存的请求数" json:"countCachedRequests"` // 缓存的请求数
	CountAttackRequests int64   `gorm:"column:countAttackRequests;comment:攻击请求数" json:"countAttackRequests"`  // 攻击请求数
	AttackBytes         int64   `gorm:"column:attackBytes;comment:攻击流量" json:"attackBytes"`                   // 攻击流量
	Day                 string  `gorm:"column:day;comment:日期YYYYMMDD" json:"day"`                             // 日期YYYYMMDD
	Hour                string  `gorm:"column:hour;comment:YYYYMMDDHH" json:"hour"`                           // YYYYMMDDHH
	TimeFrom            string  `gorm:"column:timeFrom;comment:开始时间HHMMSS" json:"timeFrom"`                   // 开始时间HHMMSS
	TimeTo              string  `gorm:"column:timeTo;comment:结束时间" json:"timeTo"`                             // 结束时间
	IsCharged           bool    `gorm:"column:isCharged;comment:是否已计算费用" json:"isCharged"`                    // 是否已计算费用
	PlanID              int64   `gorm:"column:planId;comment:套餐ID" json:"planId"`                             // 套餐ID
	Fee                 float64 `gorm:"column:fee;default:0.00;comment:费用" json:"fee"`                        // 费用
}

// TableName GalloServerDailyStat's table name
func (*GalloServerDailyStat) TableName() string {
	return TableNameGalloServerDailyStat
}
