// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloUserVerifyCode = "galloUserVerifyCodes"

// GalloUserVerifyCode 重置密码之验证码
type GalloUserVerifyCode struct {
	ID         int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Email      string `gorm:"column:email;comment:邮箱地址" json:"email"`                       // 邮箱地址
	Mobile     string `gorm:"column:mobile;comment:手机号" json:"mobile"`                      // 手机号
	Code       string `gorm:"column:code;comment:验证码" json:"code"`                          // 验证码
	Type       string `gorm:"column:type;comment:类型" json:"type"`                           // 类型
	IsSent     bool   `gorm:"column:isSent;comment:是否已发送" json:"isSent"`                    // 是否已发送
	IsVerified bool   `gorm:"column:isVerified;comment:是否已激活" json:"isVerified"`            // 是否已激活
	CreatedAt  int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	ExpiresAt  int64  `gorm:"column:expiresAt;comment:过期时间" json:"expiresAt"`               // 过期时间
	Day        string `gorm:"column:day;comment:YYYYMMDD" json:"day"`                       // YYYYMMDD
}

// TableName GalloUserVerifyCode's table name
func (*GalloUserVerifyCode) TableName() string {
	return TableNameGalloUserVerifyCode
}
