// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloHTTPPage = "galloHTTPPages"

// GalloHTTPPage 特殊页面
type GalloHTTPPage struct {
	ID                int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"`    // ID
	AdminID           int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                     // 管理员ID
	UserID            int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                        // 用户ID
	IsOn              bool   `gorm:"column:isOn;comment:是否启用" json:"isOn"`                            // 是否启用
	StatusList        string `gorm:"column:statusList;comment:状态列表" json:"statusList"`                // 状态列表
	URL               string `gorm:"column:url;comment:页面URL" json:"url"`                             // 页面URL
	NewStatus         int32  `gorm:"column:newStatus;comment:新状态码" json:"newStatus"`                  // 新状态码
	State             bool   `gorm:"column:state;default:1;comment:状态" json:"state"`                  // 状态
	CreatedAt         int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`                  // 创建时间
	Body              string `gorm:"column:body;comment:页面内容" json:"body"`                            // 页面内容
	BodyType          string `gorm:"column:bodyType;default:url;comment:内容类型" json:"bodyType"`        // 内容类型
	ExceptURLPatterns string `gorm:"column:exceptURLPatterns;comment:例外URL" json:"exceptURLPatterns"` // 例外URL
	OnlyURLPatterns   string `gorm:"column:onlyURLPatterns;comment:限制URL" json:"onlyURLPatterns"`     // 限制URL
}

// TableName GalloHTTPPage's table name
func (*GalloHTTPPage) TableName() string {
	return TableNameGalloHTTPPage
}
