// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloClientAgent = "galloClientAgents"

// GalloClientAgent Agent库
type GalloClientAgent struct {
	ID          int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name        string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	Code        string `gorm:"column:code;comment:代号" json:"code"`                           // 代号
	Description string `gorm:"column:description;comment:介绍" json:"description"`             // 介绍
	Order       int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	CountIPs    int32  `gorm:"column:countIPs;comment:IP数量" json:"countIPs"`                 // IP数量
}

// TableName GalloClientAgent's table name
func (*GalloClientAgent) TableName() string {
	return TableNameGalloClientAgent
}
