// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloServerClientBrowserMonthlyStat = "galloServerClientBrowserMonthlyStats"

// GalloServerClientBrowserMonthlyStat 浏览器统计（按月）
type GalloServerClientBrowserMonthlyStat struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	ServerID  int32  `gorm:"column:serverId;comment:服务ID" json:"serverId"`                 // 服务ID
	BrowserID int32  `gorm:"column:browserId;comment:浏览器ID" json:"browserId"`              // 浏览器ID
	Month     string `gorm:"column:month;comment:YYYYMM" json:"month"`                     // YYYYMM
	Version   string `gorm:"column:version;comment:主版本号" json:"version"`                   // 主版本号
	Count     int64  `gorm:"column:count;comment:数量" json:"count"`                         // 数量
}

// TableName GalloServerClientBrowserMonthlyStat's table name
func (*GalloServerClientBrowserMonthlyStat) TableName() string {
	return TableNameGalloServerClientBrowserMonthlyStat
}
