// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNodeGroup = "galloNodeGroups"

// GalloNodeGroup 节点分组
type GalloNodeGroup struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name      string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	ClusterID int32  `gorm:"column:clusterId;comment:集群ID" json:"clusterId"`               // 集群ID
	Order     int32  `gorm:"column:order;comment:排序" json:"order"`                         // 排序
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	State     bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
}

// TableName GalloNodeGroup's table name
func (*GalloNodeGroup) TableName() string {
	return TableNameGalloNodeGroup
}
