// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloReportNode = "galloReportNodes"

// GalloReportNode 连通性报告终端
type GalloReportNode struct {
	ID        int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	UniqueID  string `gorm:"column:uniqueId;comment:唯一ID" json:"uniqueId"`                 // 唯一ID
	Secret    string `gorm:"column:secret;comment:密钥" json:"secret"`                       // 密钥
	IsOn      bool   `gorm:"column:isOn;default:1;comment:是否启用" json:"isOn"`               // 是否启用
	Name      string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	Location  string `gorm:"column:location;comment:所在区域" json:"location"`                 // 所在区域
	Isp       string `gorm:"column:isp;comment:网络服务商" json:"isp"`                          // 网络服务商
	AllowIPs  string `gorm:"column:allowIPs;comment:允许的IP" json:"allowIPs"`                // 允许的IP
	IsActive  bool   `gorm:"column:isActive;comment:是否活跃" json:"isActive"`                 // 是否活跃
	Status    string `gorm:"column:status;comment:状态" json:"status"`                       // 状态
	State     bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	GroupIds  string `gorm:"column:groupIds;comment:分组ID" json:"groupIds"`                 // 分组ID
}

// TableName GalloReportNode's table name
func (*GalloReportNode) TableName() string {
	return TableNameGalloReportNode
}
