// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloNSQuestionOption = "galloNSQuestionOptions"

// GalloNSQuestionOption DNS请求选项
type GalloNSQuestionOption struct {
	ID        int64  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name      string `gorm:"column:name;comment:选项名" json:"name"`                          // 选项名
	Values    string `gorm:"column:values;comment:选项值" json:"values"`                      // 选项值
	CreatedAt int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
}

// TableName GalloNSQuestionOption's table name
func (*GalloNSQuestionOption) TableName() string {
	return TableNameGalloNSQuestionOption
}
