// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package v1

const TableNameGalloDNSProvider = "galloDNSProviders"

// GalloDNSProvider DNS服务商
type GalloDNSProvider struct {
	ID            int32  `gorm:"column:id;primaryKey;autoIncrement:true;comment:ID" json:"id"` // ID
	Name          string `gorm:"column:name;comment:名称" json:"name"`                           // 名称
	AdminID       int32  `gorm:"column:adminId;comment:管理员ID" json:"adminId"`                  // 管理员ID
	UserID        int32  `gorm:"column:userId;comment:用户ID" json:"userId"`                     // 用户ID
	Type          string `gorm:"column:type;comment:供应商类型" json:"type"`                        // 供应商类型
	APIParams     string `gorm:"column:apiParams;comment:API参数" json:"apiParams"`              // API参数
	CreatedAt     int64  `gorm:"column:createdAt;comment:创建时间" json:"createdAt"`               // 创建时间
	State         bool   `gorm:"column:state;default:1;comment:状态" json:"state"`               // 状态
	DataUpdatedAt int64  `gorm:"column:dataUpdatedAt;comment:数据同步时间" json:"dataUpdatedAt"`     // 数据同步时间
}

// TableName GalloDNSProvider's table name
func (*GalloDNSProvider) TableName() string {
	return TableNameGalloDNSProvider
}
